### ISSUE TITLE
Adding hover effect to buttons of the fruit 

### ISSUE THREAD

**Issue by YashBawa** [Rakesh9100/Click-The-Edible-Game#1]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The hover effect effect onto the buttons will be added on the website to make it look even better styled . Each fruit button shall be added with a little bit of styling . To make it look Attractive . 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by YashBawa** [comment]
I would like to work for adding this feature under Hacktoberfest @Rakesh9100 would you please review and assign.

**Comment by Rakesh9100** [comment]
Okay, you can work @YashBawa

**Comment by YashBawa** [comment]
Thank you @Rakesh9100 .

**Comment by RathoreAbhiii** [comment]
Has a pull request been already merged regarding this issue? If not, can I work on the same? @Rakesh9100

**Comment by YashBawa** [comment]
@RathoreAbhiii am currently working on this issue please find another issue . Thank You

**Comment by RathoreAbhiii** [comment]
> @RathoreAbhiii am currently working on this issue please find another issue . Thank You

Cool, Appreciate it!

**Comment by YashBawa** [comment]
@Rakesh9100 I have made a PR for this issue please review and verify it.
