### ISSUE TITLE
Update the instruction

### ISSUE THREAD

**Issue by khushimarothi** [Rakesh9100/Click-The-Edible-Game#101]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to update the instructions box. 

The instructions are not clear in one glance since the font weight is same for everything. also I will add some illustration to make that box look beautiful and user friendly.

### Screenshots

![Screenshot (39)](https://user-images.githubusercontent.com/85816852/223901090-406cfea8-4313-41b1-b56c-408919fd87c9.png)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Upload the screenshot again.

**Comment by Rakesh9100** [comment]
Go ahead, upload the screenshot again. @khushimarothi

**Comment by khushimarothi** [comment]
![Screenshot (39)](https://user-images.githubusercontent.com/85816852/223901090-406cfea8-4313-41b1-b56c-408919fd87c9.png)
