### ISSUE TITLE
[Enhancement] Redesigning the Scrollbar

### ISSUE THREAD

**Issue by pooranjoyb** [Rakesh9100/Click-The-Edible-Game#102]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The scrollbar in the screen 2 seems quite off as it doesnot match the color scheme of the webpage. 

### I would like to redesign that will match the project theme. 
Please assign me with this issue. @Rakesh9100 😃 

### Screenshots

![demo26](https://user-images.githubusercontent.com/90945182/223843806-8c701176-f39c-40ed-b223-5451c08dbdee.png)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigned, Proceed @pooranjoyb
