### ISSUE TITLE
Modification in one icon

### ISSUE THREAD

**Issue by zugzwang03** [Rakesh9100/Click-The-Edible-Game#104]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

There is an arrow icon while the game is on signifying that on clicking there, the website redirects to the homepage, but it is ambiguous as the user might consider an arrow symbol for expansion of the side navbar. Therefore, I feel placing a home icon might suit better there in terms of readability. 
![image](https://user-images.githubusercontent.com/95460021/224113323-4da73c98-0901-4498-8b3b-ef51e73f3e82.png)
If you want to make this change, you can assign me this issue under JWOC'23.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Not required. Pls find other issues to work on.
