### ISSUE TITLE
[Feature] Adding High Score on Game Over

### ISSUE THREAD

**Issue by pooranjoyb** [Rakesh9100/Click-The-Edible-Game#108]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

## Outcome
- This will increase overall quality of the game and give it a professional outlook.
- Player will try to beat his own Highscore, resulting a player to spend more time in the Game.

## Workflow : 
**It will take some time to complete this task**. 
It's quite difficult to execute as 
- we have to store the Highscore and update it each time with the new score
- comparing with previous scores
- Also make sure that scores will be invalid for other timers and is valid for one particular gameplay time.
- We will have to reset the Highscore if player chooses a separate time of gameplay. 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigning @pooranjoyb 
You can take your own time to complete, but before JWOC ends.
