### ISSUE TITLE
Add New Edibles category

### ISSUE THREAD

**Issue by S-ishita** [Rakesh9100/Click-The-Edible-Game#110]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add bakery products as a new category which will have:

- different cards of bakery products
- similar UI to other cards
- same functionality as other items

Please assign this issue to me under JWOC

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Okay proceed but make sure to add every PNG images compressed to less than 50kb @S-ishita
