### ISSUE TITLE
Add report a bug page

### ISSUE THREAD

**Issue by S-ishita** [Rakesh9100/Click-The-Edible-Game#113]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to design a bug reporting page where anyone  can submits bugs in website.
Please assign this issue to me under JWOC

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
I don't think it's required but if you have any good idea of design and implementation then pls specify in detail @S-ishita

**Comment by S-ishita** [comment]
page would have similar design to the website.. and since it is a game a bug reporting page will enhance user experience..

**Comment by Rakesh9100** [comment]
Where will the reported bug be? Will it come to my mail, or it will remain listed on your created page ?

**Comment by S-ishita** [comment]
The messages will be delivered to the user's email address directly through the redirections of the website.
No PHP, NodeJS, Express Server or any backend code required

**Comment by Rakesh9100** [comment]
I am assigning to you but if this change will not seem good for the project, then issue will be closed @S-ishita

**Comment by S-ishita** [comment]
ok..for now i shall raise pr for frontend part only 
if it seems good to you then i will do the redirecting part as well

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC

**Comment by Rakesh9100** [comment]
@S-ishita Status of your work
