### ISSUE TITLE
Add new edible 

### ISSUE THREAD

**Issue by Daffodilgithub** [Rakesh9100/Click-The-Edible-Game#114]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add seafood section. Can you please assign this issue to me under JWOC?

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Not required. 5 categories are sufficient. Try to find other issues to work. @Daffodilgithub
