### ISSUE TITLE
Link is not working in README.md

### ISSUE THREAD

**Issue by Daffodilgithub** [Rakesh9100/Click-The-Edible-Game#116]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

After clicking on this live project link ,this page is being shown. I want to fix this issue. Can you please assign it to me under JWOC?

### Screenshots

![Screenshot (77)](https://user-images.githubusercontent.com/98342622/224535871-93c27a45-f49a-49e2-bde6-c5978958494a.png)
![Screenshot (78)](https://user-images.githubusercontent.com/98342622/224535875-ebc455b4-aeaf-4cac-940f-f67b6ac2d744.png)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigned @Daffodilgithub
