### ISSUE TITLE
Language Translator

### ISSUE THREAD

**Issue by ritika728** [Rakesh9100/Click-The-Edible-Game#119]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hey @Rakesh9100  , I would like to open this issue under JWOC.

### Screenshots

- User can translate the text into any language with just one click.
- user can select the preferred language from all the possible languages (100+ including hindi) available on Google
- after selecting a specific language, user will be able to :
   - again translate the page by choosing new language
   - showing the original language
   - turn off the translation for that site

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Is the translation feature really necessary ? Since there is not much text in this gaming website @ritika728

**Comment by ritika728** [comment]
@Rakesh9100 it is an extra feature which is implemented on many of the websites these days. If you'll say, I'll work on this

**Comment by Rakesh9100** [comment]
Okay proceed, assigned @ritika728
