### ISSUE TITLE
Add footer for copyright claim of the game

### ISSUE THREAD

**Issue by radhika141** [Rakesh9100/Click-The-Edible-Game#12]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add a footer to the site for the copyright claim  

### Screenshots

![image](https://user-images.githubusercontent.com/105503411/196733870-f3016fe6-2811-40c0-9c68-3cd57a540db0.png)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
It's not needed @radhika141
