### ISSUE TITLE
Create Error Page 

### ISSUE THREAD

**Issue by TuhinBanerjee31** [Rakesh9100/Click-The-Edible-Game#122]
### Prerequisites

- [X] I am an Open Source Contributor
- [x] I checked to make sure that this issue has not already been filed

### Description

Want to create a 404 responsive error page for the website.

### Screenshots

I want to work on this issue under JWOC

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed @TuhinBanerjee31 Make a good, well-designed animated page.

**Comment by Awesomeasma** [comment]
@Rakesh9100 
I would like to work on this under JWOC

**Comment by Rakesh9100** [comment]
One mentee is already working @Awesomeasma Try to find other issues to work
