### ISSUE TITLE
[Feature] Displaying All the Scores in Descending Order

### ISSUE THREAD

**Issue by pooranjoyb** [Rakesh9100/Click-The-Edible-Game#123]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Workflow : 
- [x] Create an `Scores` Element in the DOM
- [x] Initialize an `Scores Array` that will keep storing the Player's Scores
- [x] Sort the `Scores Array` in reverse order to make sure it's descending order.
- [x] Serve the updated Element back to the DOM.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigned @pooranjoyb
