### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Daffodilgithub** [Rakesh9100/Click-The-Edible-Game#127]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to update the introduction part according to the project. Please assign this issue to me under JWOC.

### Screenshots

![Screenshot (86)](https://user-images.githubusercontent.com/98342622/225114207-381ac87a-ada5-452f-8201-eea26636d9ed.png)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed @Daffodilgithub

**Comment by Awesomeasma** [comment]
@Rakesh9100 
I would like to work on this under JWOC
