### ISSUE TITLE
Updating Footer

### ISSUE THREAD

**Issue by Viveksati5143** [Rakesh9100/Click-The-Edible-Game#129]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The footer style should match the standards of a footer.

### Screenshots

Enhancing Footer under JWOC

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
The footer present is fine and good. Brief the change you will do or provide any reference screenshot. @Viveksati5143

**Comment by Viveksati5143** [comment]
@Rakesh9100 The standard footer should be present in the center instead of left.
Also, i can enhance the footer's colour according to you

**Comment by Rakesh9100** [comment]
Assigning to you, but issue will be closed if it will not look a good enhancement @Viveksati5143
