### ISSUE TITLE
Design UI of home screen

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/Click-The-Edible-Game#13]
You can animate the home screen and make better UI (Ex: include animations)

**Comment by yeager404** [comment]
Would like to work on this issue as well

**Comment by sandeeprawat28** [comment]
Please assign this issue to me.
I will improve the UI design of this project

**Comment by taniaban2712** [comment]
I want to work on this issue under JWOC

**Comment by Rakesh9100** [comment]
@taniaban2712 Assigning this issue to you, Go for it.

**Comment by ManasaKaza** [comment]
I want to work on this issue under JWOC

**Comment by kushaljgec2025** [comment]
I want to work on this issue under JWOC

**Comment by ADITI-2003** [comment]
Hello mentor,
I want to work on this issue under JWOC. 
Thank you

**Comment by Rakesh9100** [comment]
@ManasaKaza Would you like to work ?

**Comment by ManasaKaza** [comment]
Yeah

**Comment by Rakesh9100** [comment]
Assigning to you @ManasaKaza

**Comment by DeepanshuRohilla15** [comment]
Hello sir, I would like to work on this.
I am definitely improve the UI design of home screen.
I have done a lot of designing and UI work 
I am in core team member of Design Content at GDSC DCRUST so I will do good UI to this project.

**Comment by Rakesh9100** [comment]
The issues are assigned on the basis of FCFS. So if they are unable to complete, then will assign to you. Till then, try creating new issues if you find any and work on them. @DeepanshuRohilla15

**Comment by Code1705** [comment]
I want to style the home page and contribute to this issue under JWOC , please assign me.

**Comment by Rakesh9100** [comment]
@ManasaKaza Status of your work

**Comment by deepbeatz** [comment]
I want to work on this under JWOC

**Comment by Code1705** [comment]
@Rakesh9100 I want to design the UI of the home screen please assign me under Jwoc.

**Comment by Rakesh9100** [comment]
@DeepanshuRohilla15 Would you like to work ?

**Comment by Code1705** [comment]
HEY ! @Rakesh9100  i want to contribute to this issue, please assign me under jwoc.

**Comment by ADITI-2003** [comment]
> Hello mentor, I want to work on this issue under JWOC. Thank you

Hello @Rakesh9100 , reminder for the request made under jwoc.
Thank you

**Comment by Rakesh9100** [comment]
My mistake @ADITI-2003, As you can see, UI is already changed from before. So If you like to work more on this, then pls specify the idea what UI change or enhancement you will do.

**Comment by ADITI-2003** [comment]
Due to the footer added, the vegetable row is getting hidden a bit, so can reposition that and will try to work on dark mode UI if I would.

> My mistake @ADITI-2003, As you can see, UI is already changed from before. So If you like to work more on this, then pls specify the idea what UI change or enhancement you will do.

**Comment by Rakesh9100** [comment]
Issue is still open, but a mentee made dark theme and also improved UI in another issue.
But still I need the enhancement like
A. Light theme background is simple pink which is not looking much good, you can put good color of linear gradient animated or more good similar idea if you have.
B. Dark theme background color can also be enhanced to much better. So, work on these. @ADITI-2003

**Comment by Rakesh9100** [comment]
Ok then go ahead, assigned to you @ADITI-2003 And yes, if the work would be too good which I would personally like, then the difficulty tag will also be increased to hard.
So give your best.

**Comment by ADITI-2003** [comment]
ok @Rakesh9100 , will give my best

**Comment by Atul-8115** [comment]
I would like to work on this issue please assign it to me

**Comment by vatan-prakash** [comment]
I want to work on this issue under jwoc

**Comment by Rakesh9100** [comment]
@ADITI-2003 Status of your work

**Comment by Code1705** [comment]
I want to contribute to this issue by making certain changes in the css file , please assign me  under JWOC.

**Comment by ADITI-2003** [comment]
> @ADITI-2003 Status of your work

Sir I am on it but facing issues with fixing the error, please give me time till tonight and I'll update you about the progress.

**Comment by ADITI-2003** [comment]
> @ADITI-2003 Status of your work

@Rakesh9100 , the code is ready will push it by today evening after my classes for sure, please grant me a little more time for today. 
Thank you

**Comment by Rakesh9100** [comment]
Okay granted only till today @ADITI-2003

**Comment by Code1705** [comment]
Yaa yaa definately

**Comment by Rakesh9100** [comment]
Okay then proceed from now @Code1705

**Comment by Rakesh9100** [comment]
Status of your PR @Code1705 You have time only for today
