### ISSUE TITLE
Enhancement: Allow Custom GamePlay Time Durations

### ISSUE THREAD

**Issue by SoumyadevSaha** [Rakesh9100/Click-The-Edible-Game#132]
## Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Feature Enhancement @ SloP 3.0
I've made an enhancement to the "Choose GamePlay Time" feature in the "Click The Edible Game" game. Currently, the game offers predefined time slots of 30 seconds, 1 minute, 1.5 minutes, and 2 minutes. I've modified the code to allow users to select a custom time duration between 30 seconds and 5 minutes, providing a more flexible gaming experience.

### Proposed Changes
- [x] Update the "Choose GamePlay Time" section to include a time range slider that allows users to select any time duration between 30 seconds and 5 minutes.
- [x] Update the game logic so that the user can play as long as their desired duration seamlessly.
- [x] Update the UI to maintain repsonsiveness of the game.

### Motivation
This change enhances the user experience by giving players more control over their game duration. It can make the game more engaging and suitable for a wider range of players who may prefer different time limits.

### Additional Notes
Please review this enhancement request, and if it aligns with the project's goals and standards, I'd be happy to create a pull request to implement these changes. Your feedback and guidance are highly appreciated.

## Screenshots

![gameplaytime-box-change](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/86418216/1627447c-8e6a-4b22-ac17-e252b222dcb9)

## Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigned, Start working @SoumyadevSaha
