### ISSUE TITLE
Enhancement: Add explosive bombs along with edibles in the game

### ISSUE THREAD

**Issue by SoumyadevSaha** [Rakesh9100/Click-The-Edible-Game#134]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Feature Enhancement @ SloP 3.0
I've made an enhancement to the "Click The Edible Game" by introducing bombs and lifelines to the game. Currently, the game is about clicking as many edibles as possible within a set time frame. This enhancement adds a new challenge to the game.

### Proposed Changes
- [x] Introduce bombs as a part of the game.
- [x] Limit the number of active bombs on the screen at any given time (MAX_number of bombs).
- [x] When a user clicks an edible, there's a 50% chance a new bomb appears, provided the number of active bombs is below the maximum limit.
- [x] Bombs have a limited lifespan, and if they are not clicked within a certain time, they disappear.
- [x] Set a rule that if a user clicks on 3 bombs, the game is over, regardless of the remaining time on the timer.
- [x] Implement UI elements to display the number of lives left.
- [x] Integrate new sound and animation on bomb explosion. 

### Motivation
This change adds an exciting twist to the game by introducing the risk of bombs. Players need to balance clicking edibles for points and avoiding bombs to stay in the game. It adds an element of strategy and challenges players to manage their moves effectively.

### Additional Notes
Please review this enhancement request, and if it aligns with the project's goals and standards, I'd be happy to create a pull request to implement these changes. Your feedback and guidance are highly appreciated.

### Screen Shot 1
<img width="1436" alt="issue2_1" src="https://github.com/Rakesh9100/Click-The-Edible-Game/assets/86418216/6e9cae39-e123-47bf-81da-199cf39df31c">

### Screen Shot 2
<img width="1436" alt="issue2_2" src="https://github.com/Rakesh9100/Click-The-Edible-Game/assets/86418216/eeca7f49-2d81-4e55-beba-038945c91984">

### Screen Shot 3
<img width="1434" alt="issue2_3" src="https://github.com/Rakesh9100/Click-The-Edible-Game/assets/86418216/10e18abf-997c-4120-b037-4050705cf97f">

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigned @SoumyadevSaha Proceed!!
