### ISSUE TITLE
Improvement in Scrollbar responsiveness to smaller screen sizes

### ISSUE THREAD

**Issue by gjyotk** [Rakesh9100/Click-The-Edible-Game#135]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

## Changes made:

Made an improvement in the responsiveness of the scrollbar for screen widths of less than 1440px. Currently, for width less than 1440px, double vertical scrollbars appear (a result of content overflowing and not adjusting to smaller screen sizes). I've rectified the relevant query for scrollbar responsiveness.

## Objective: 

- Updation in UI to maintain the responsiveness of vertical scrollbar
- Enhance user experience of the website

I would appreciate your review of this request and would be delighted to initiate the process of creating a pull request for the implementation of this proposed modification. Your valuable feedback and guidance would be greatly welcomed.

### Screenshots

<img width="710" alt="Screenshot 2023-10-26 at 12 10 13 AM" src="https://github.com/Rakesh9100/Click-The-Edible-Game/assets/112189682/c5ed9a1b-5dd5-4de6-b69b-7f675ebdc338">

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigned @gjyotk Start working!!
