### ISSUE TITLE
Feature: Adding new sound effects for better UX

### ISSUE THREAD

**Issue by SoumyadevSaha** [Rakesh9100/Click-The-Edible-Game#138]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

## Addition of new sound effects for better UX @SloP 3.0
Adding new Sound files (mp3/wav or such) to notify gameover, updating the sound effect of clicking the edible, and other such features (like playing a BGM for the game in a loop and others).

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Can you pls specify like which type of sound and what exactly you want to add/change as already 3 sound files are present in the repo @SoumyadevSaha

**Comment by SoumyadevSaha** [comment]
> Can you pls specify like which type of sound and what exactly you want to add/change as already 3 sound files are present in the repo @SoumyadevSaha

Other than the 3 sound files, namely one which plays after selecting an edible and before selecting time frame, one which plays on clicking on an edible, and one whne a bomb explodes, I am willing to add 3 more sound files. 1. A game BGM (which is repeated on loop starting from when the game starts, and ends when it is gameover, 2. A gameover sound, which is played, when the game gets over (instead of the BGM), and 3. Another background music which is played when one is not playing the game, but is in the main menu, or is reading the instructions or have the game paused, etc.

**Comment by Rakesh9100** [comment]
Seems interesting, proceed @SoumyadevSaha

**Comment by Rakesh9100** [comment]
Okay, Go ahead @SoumyadevSaha
