### ISSUE TITLE
Update: Instruction box in the game

### ISSUE THREAD

**Issue by SoumyadevSaha** [Rakesh9100/Click-The-Edible-Game#139]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

## Updating the instruction box in the game @SloP 3.0
Update the Instruction box content in the game to let players know about introduction of the new feature (the bombs) and that in case they click on a bomb, it is not an immediate game over, but they still will have 2 lives remaining.

## New instruction might look something like:

<img width="1435" alt="Screenshot 2023-10-27 at 8 55 52 PM" src="https://github.com/Rakesh9100/Click-The-Edible-Game/assets/86418216/1873f7eb-f154-4246-83a2-958063013f66">

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigned @SoumyadevSaha
