### ISSUE TITLE
Add some more Edible items

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/Click-The-Edible-Game#14]

**Comment by Shantanu-Meta** [comment]
Hey i want to contribute

**Comment by Sowham-3098** [comment]
I want to contribute in this.

**Comment by Beingfarazkhan** [comment]
I would like to Contribute Towards this issue 🚀

**Comment by Atul-8115** [comment]
Please assign this issue to me.

**Comment by Daffodilgithub** [comment]
I want to work on this issue under JWOC 2023 . Can you please assign me this issue ?

**Comment by ADITI-2003** [comment]
Hello mentor,
I want to add more edible items, please assign to me this issue.
Thank you.

**Comment by vk20july** [comment]
I want to work on this issue under JWOC

**Comment by taniaban2712** [comment]
I want to work on this issue under JWOC.

**Comment by Sowham-3098** [comment]
I can contribute to this

**Comment by AK-shat-JAIN** [comment]
Hi want to do this task

**Comment by manya0210** [comment]
Hello sir ..I want to contribute to this issue under jwoc

**Comment by AgnishaDe** [comment]
I want to work on this issue under JWOC

**Comment by ADITI-2003** [comment]
Hello mentor,
I want to add more edible items, please assign to me this issue under JWOC.
Thank you.

**Comment by Rakesh9100** [comment]
@Beingfarazkhan are you working under JWOC ?

**Comment by Rakesh9100** [comment]
@Daffodilgithub Assigning this issue to you, Best of luck

**Comment by Rakesh9100** [comment]
@ADITI-2003 Assigning this to you, go ahead

**Comment by ADITI-2003** [comment]
Ok mentor, Thank you. I am on it.
