### ISSUE TITLE
Adding twitter icon in footer

### ISSUE THREAD

**Issue by baekusboo** [Rakesh9100/Click-The-Edible-Game#141]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I would like to add twitter icon to the social media icons! Please assign me this issue under hacktoberfest label.

### Screenshots

<img width="938" alt="image" src="https://github.com/Rakesh9100/Click-The-Edible-Game/assets/83155556/bd6d917e-5ec9-42d8-a400-26d37775eea6">

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Not needed. Pls find and work on other good issues @baekusboo
