### ISSUE TITLE
Improvement: Adding UI for scrollbar in dark mode

### ISSUE THREAD

**Issue by gjyotk** [Rakesh9100/Click-The-Edible-Game#143]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

In this issue, i am proposing an update in Scrollbar to match the dark-colour-aesthetic when dark mode is turned on. This will enhance its visibility and improve the overall user experience.

## Objective:
- [x] Updation in UI to maintain the dark-theme in scrollbar when using dark mode
- [x] Enhance user experience of the website

I would appreciate your review of this request and would be delighted to initiate the process of creating a pull request for the implementation of this proposed modification. Your valuable feedback and guidance would be greatly welcomed.

### Screenshots

<img width="1197" alt="Screenshot 2023-10-29 at 12 17 09 AM" src="https://github.com/Rakesh9100/Click-The-Edible-Game/assets/112189682/6e69805f-9a04-4be5-8b0c-e696a0aa8d7b">

<img width="1194" alt="Screenshot 2023-10-29 at 12 24 52 AM" src="https://github.com/Rakesh9100/Click-The-Edible-Game/assets/112189682/59a460a6-39e1-452b-a922-efd6a8030664">

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigned @gjyotk Proceed!!
