### ISSUE TITLE
Feature: Uploading Edible functionality

### ISSUE THREAD

**Issue by SoumyadevSaha** [Rakesh9100/Click-The-Edible-Game#155]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Uploading an Edible @ SloP 3.0
- Although the list to choose one's favourite edible, before playing is quite vast, there remains a possibility an user might not find their favourite edible in the list.
- As such, adding a custom upload button so that the user can upload their own favourite edible and then play with it, makes the game even more interactive.

### Screen-shot 1
<img width="1439" alt="Screenshot 2023-11-17 at 5 07 28 PM" src="https://github.com/Rakesh9100/Click-The-Edible-Game/assets/86418216/be6e611c-d696-48f0-afa0-fb62b76b4f38">

### Screen-shot 2
<img width="1435" alt="Screenshot 2023-11-17 at 5 07 52 PM" src="https://github.com/Rakesh9100/Click-The-Edible-Game/assets/86418216/ea4c5e56-171c-4e75-961d-2cca02b7acda">

### Screen-shot 3
<img width="1421" alt="Screenshot 2023-11-17 at 5 08 24 PM" src="https://github.com/Rakesh9100/Click-The-Edible-Game/assets/86418216/966f3455-7ad7-4761-9546-ccc8f4993ca5">

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigned @SoumyadevSaha Go ahead!!

**Comment by SoumyadevSaha** [comment]
Made the PR @Rakesh9100
