### ISSUE TITLE
Improve the UI of the website 

### ISSUE THREAD

**Issue by sambitsingha** [Rakesh9100/Click-The-Edible-Game#157]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

- **The frontend UI of the website needs to be updated according to the theme of the project, that is , a game.** 
- **Likewise the **_favourite fruit part_** needs to updated for enhancing user experiance.**

### Screenshots

Here is a sample of a website whose UI  I have updated according to the base of the website

## Original Look 

![Screenshot (120)](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/110420002/61f7d044-aedc-4365-a889-15bc02c1f204)

## New Look I added

![Screenshot (119)](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/110420002/f7821bbe-54e4-46d9-ba5c-281b4e7e5d49)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
SWOC begins on 1st Jan,, 2024! You will be assigned in new year!!😀 @sambitsingha

**Comment by vishal0316** [comment]
> SWOC begins on 1st Jan,, 2024! You will be assigned in new year!!😀 @sambitsingha
so new issues will be assigned ?

**Comment by krishnagitcontri** [comment]
I am working on this issue and i wil Raise my PR on JAN 1.

**Comment by Rakesh9100** [comment]
You can't raise the PR until you are assigned this issue @krishnagitcontri 
Issues are assigned at FCFS!!

**Comment by sambitsingha** [comment]
> SWOC begins on 1st Jan,, 2024! You will be assigned in new year!!😀 @sambitsingha

Alright @Rakesh9100 , will wait till 1 Jan till this is assigned. :)

**Comment by Bhuvangoyal466** [comment]
Hi I want to work on this

**Comment by sambitsingha** [comment]
@Rakesh9100 Would I start working if you assign !!

**Comment by Rakesh9100** [comment]
Assigned, Start working!! @sambitsingha

**Comment by Rakesh9100** [comment]
@sambitsingha Any update of your PR

**Comment by sambitsingha** [comment]
I did something .. but was not satisfied myself :) . Still working on it

**Comment by Rakesh9100** [comment]
Sure, you can continue!! Just needed the update, Thanks @sambitsingha

**Comment by Rakesh9100** [comment]
Sure, you can continue!! Just needed the update @sambitsingha

**Comment by Rakesh9100** [comment]
@sambitsingha Status pls

**Comment by sambitsingha** [comment]
@Rakesh9100 Doing ASAP

**Comment by sambitsingha** [comment]
@Rakesh9100 
![Screenshot (130)](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/110420002/094c58f9-8769-47ea-92b4-74119768981c)
![Screenshot (131)](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/110420002/88321716-2092-4bac-bd94-a14a5f1bab21)
![Screenshot (132)](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/110420002/197f816a-6995-4e95-95b7-ee548d977ef8)
![Screenshot (133)](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/110420002/b2a2b295-9a8b-422a-be1c-67fa67090d2e)

The background will zoom down as the user reaches down to play the game. It is not possible to show in the beginning as it is being restricted by the ``main.js`` file . 

A entire change is not possible for it would require changing the js file , that would possibly break the website.

However I am open to delicate changes that is required. 

P.S -  If this is fine , I will do a PR

**Comment by Rakesh9100** [comment]
![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/73993775/bffe53dd-1e62-45c6-b817-05c479ba4901)

Is this section similar to Carousel or scrollable left to right?
Do highlight the background of footer section more to make it visible as footer section @sambitsingha

**Comment by Rakesh9100** [comment]
![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/73993775/bffe53dd-1e62-45c6-b817-05c479ba4901)

### Is this section similar to Carousel or scrollable left to right?
### Do highlight the background of footer section more to make it visible as footer section.

![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/73993775/3d88fc7b-0b64-4b5f-b1ec-1d6219c562ec)

### In this case, footer is not visible properly @sambitsingha

**Comment by sambitsingha** [comment]
- I haven't made it scrollable. 
- Alr I am updating the footer .
If this is done , finally I can add a ScrollReveal effect which will reveal each element one by one on scroll.

**Comment by Rakesh9100** [comment]
A;lso this background seems most suitable for the dark theme.
I need one good appealing background for the light theme @sambitsingha

**Comment by sambitsingha** [comment]
I am looking a good light theme background. 
In the mean time , I am also adjusting the dark mode background

**Comment by sambitsingha** [comment]
## Light theme 
![bg-light](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/110420002/aa72d772-7ee8-46a8-9198-b9f3f7620fe0)
## Dark theme
![bg-dark](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/110420002/2745f8e5-3b33-4c62-9912-3f15cc4d0bb9)

Are you ok with this ??

## Updated footer - 
![Screenshot (136)](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/110420002/5b7135c3-6932-4056-99fd-f63796d36fea)

**Comment by Rakesh9100** [comment]
Yes, footer is fine but adjust it again afterwards based on light and dark background you will put.

And also your sample background consists of houses, trees, mountains in dark theme background which is not needed. If these comes then viewing the text would be the problem. Include some good appealing but kind of plane background @sambitsingha

**Comment by sambitsingha** [comment]
I would want to use these backgrounds. As for making the text visible and not difficult to read , that would be first priority

**Comment by Rakesh9100** [comment]
Okay then, will see in the deploy preview when you will create the PR @sambitsingha

**Comment by Rakesh9100** [comment]
The current UI is fine. We don't need any change for now. Pls work on other new issues and get it assigned @sambitsingha
