### ISSUE TITLE
Improve the footer 

### ISSUE THREAD

**Issue by VardaPanchal005** [Rakesh9100/Click-The-Edible-Game#159]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I will improve the footer of the web page and improve the UI of the footer and also make the social media links aligned with the text

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
@VardaPanchal005 Assigned, proceed!!

**Comment by VardaPanchal005** [comment]
why did i get unassigned?

**Comment by Rakesh9100** [comment]
You are not unassigned but Are you working on this @VardaPanchal005 
No updates of your work or PR.

**Comment by VardaPanchal005** [comment]
because of my ongoing exams i will update it soon

**Comment by KhushiRawat29** [comment]
@Rajesh9100 Can you please assign this issue to me.

**Comment by VardaPanchal005** [comment]
This is already assigned to me please open another issue

**Comment by KhushiRawat29** [comment]
your issue is a little unclear. Can you few screenshots of what you will be working on ?

**Comment by KhushiRawat29** [comment]
@VardaPanchal005

**Comment by VardaPanchal005** [comment]
> your issue is a little unclear. Can you few share screenshots of what you will be working on ?

I already described what I will be working on please make your own issue

**Comment by KhushiRawat29** [comment]
@VardaPanchal005 I found a bug , it is kind of related to footer too( I will not change footer). I just want to know if it is already under your issue or not. Just for clarification.

**Comment by VardaPanchal005** [comment]
My issue is to improve the UI only you can go ahead and fix the bug

**Comment by Rakesh9100** [comment]
@VardaPanchal005 When will you open your PR since its been 5 days assigned to you ?

**Comment by VardaPanchal005** [comment]
I will complete it in 3 days my exams are ongoing that’s why

**Comment by KhushiRawat29** [comment]
@VardaPanchal005 okay thanks

**Comment by Rakesh9100** [comment]
@VardaPanchal005 PR status
