### ISSUE TITLE
Add Sound effects

### ISSUE THREAD

**Issue by EmberTSeal** [Rakesh9100/Click-The-Edible-Game#16]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Currently the game does not have any sound effects when points are scored or the play button is clicked. I would like to add them.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by purbakundu** [comment]
i want to contribute

**Comment by purbakundu** [comment]
yes I am a contributor under JWOC

**Comment by Rakesh9100** [comment]
Assigning this issue to you @purbakundu, Go for it

**Comment by Rakesh9100** [comment]
@purbakundu provide the status of your work

**Comment by Ritu-2001** [comment]
i want to add sound effect please assign me under jwoc

**Comment by Rakesh9100** [comment]
Assigning to you @Ritu-2001

**Comment by Shreyan-12345** [comment]
@Rakesh9100 is it still unsolved, then pls assign it to me under JWOC

**Comment by Rakesh9100** [comment]
Sure, start working @Shreyan-12345

**Comment by Rakesh9100** [comment]
Yes sure, you have the time @Shreyan-12345

**Comment by ADITI-2003** [comment]
Hello mentor,
I want to contribute to this issue under JWOC, please assign.
Thank you

**Comment by Rakesh9100** [comment]
@Shreyan-12345 Status of your PR

**Comment by Shreyan-12345** [comment]
@Rakesh9100 I had some personal issues back sorry

**Comment by deepbeatz** [comment]
I want to work on this under JWOC

**Comment by vk20july** [comment]
I want to work on this issue under JWOC
never done any task in this repository

**Comment by Rakesh9100** [comment]
> @Rakesh9100 I had some personal issues back sorry

So will you do this issue or not ?

**Comment by Rakesh9100** [comment]
> I want to work on this issue under JWOC never done any task in this repository

You can try creating new issues, since the first who comments will be assigned first and then next to next.

**Comment by Ritu-2001** [comment]
@rakaesh assign me for this issue under jwoc

**Comment by Rakesh9100** [comment]
Complete the assigned issue first @Ritu-2001

**Comment by Rakesh9100** [comment]
@ADITI-2003 Do you want to work ?

**Comment by ADITI-2003** [comment]
> @ADITI-2003 Do you want to work ?

yes @Rakesh9100

**Comment by Rakesh9100** [comment]
Okay then start working @ADITI-2003

**Comment by ADITI-2003** [comment]
> Okay then start working @ADITI-2003

@Rakesh9100 , have made PR #65 for this issue, please review it. 
Thank you
