### ISSUE TITLE
Enhance the UI for light icon and pause button

### ISSUE THREAD

**Issue by sagarbee** [Rakesh9100/Click-The-Edible-Game#160]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Change light and pause icons' colors for clarity.
Fix red background mismatch in light and dark modes.
Enhance overall user experience.

### Screenshots

https://github.com/Rakesh9100/Click-The-Edible-Game/assets/65588552/f25af075-d471-4bb3-b7ad-a3b135936c88

https://github.com/Rakesh9100/Click-The-Edible-Game/assets/65588552/b885e1d6-b104-4347-80d0-bc508ecfc0e3

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by sagarbee** [comment]
please assign this issue to me under SWOC 2024

**Comment by Rakesh9100** [comment]
Assigned, Go ahead!! @sagarbee
