### ISSUE TITLE
[Score counter is colliding with instructions Button] 

### ISSUE THREAD

**Issue by RehanChalana** [Rakesh9100/Click-The-Edible-Game#161]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

i would like to fix the position of the score counter 

### Screenshots

![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/139042983/a6423351-663a-412a-bead-38bb06af9b60)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
@RehanChalana Start working, assigned!!
