### ISSUE TITLE
BUG _ Drag the items

### ISSUE THREAD

**Issue by sanketshinde3001** [Rakesh9100/Click-The-Edible-Game#162]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

i'll remove this bug..

### Screenshots

Uploading Recording 2024-01-01 215400.mp4…

### Code of Conduct

- [x] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Pls clarify your issue, video is not visible @sanketshinde3001

**Comment by sanketshinde3001** [comment]
Here is bug @Rakesh9100 


https://github.com/Rakesh9100/Click-The-Edible-Game/assets/126979961/ee0d6d88-9d95-46fc-ac63-bea8e2df09fa

**Comment by Rakesh9100** [comment]
Proceed!! @sanketshinde3001

**Comment by sanketshinde3001** [comment]
https://github.com/Rakesh9100/Click-The-Edible-Game/assets/126979961/cf73b05d-ef24-4a88-a446-3e39e5f98c9c


Issue Solved..
Also it is versatile for all types of browsers.
can i do PR ?
