### ISSUE TITLE
Change Light UI to make it more interactive

### ISSUE THREAD

**Issue by sagarbee** [Rakesh9100/Click-The-Edible-Game#165]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

enhance main screen by modifying gradients and fonts

### Screenshots

![Screenshot (138)](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/65588552/377f139f-acc0-4829-a53f-5ba5f0450763)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Do try to work on the suggested changes in your previous PR and issue @sagarbee

**Comment by Rakesh9100** [comment]
Pls do work on the suggested changes in your previous PR and issue @sagarbee

**Comment by vrun1208** [comment]
Hey!, @Rakesh9100 I want to work on this issue

**Comment by Rakesh9100** [comment]
Issue already exist for enhancement of UI. Pls create new issues @sagarbee
