### ISSUE TITLE
 Enhancing User Experience with Interactive Mouse Pointer

### ISSUE THREAD

**Issue by ayushichoudhary-19** [Rakesh9100/Click-The-Edible-Game#166]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The current gaming website utilizes a standard mouse cursor, and I believe we can significantly enhance the user experience by introducing an interactive and themed mouse pointer. An engaging cursor can add an extra layer of immersion and excitement for users navigating the gaming interface.

I would like to work on the same, so please assign it to me.

### Screenshots

This is the pointer I want to incorporate on the landing page. 

[screen-capture (9).webm](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/73214455/a8ae49c2-86fe-4a84-ba8e-2b69ebcdce12)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed!! Make sure to reduce the size of the circle which is surrounding the cursor @ayushichoudhary-19

**Comment by Rakesh9100** [comment]
@ayushichoudhary-19 Status of your PR
