### ISSUE TITLE
Music Starts When We Do Some Work on The Webpage

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [Rakesh9100/Click-The-Edible-Game#169]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I Would Like To Update The JavaScript Code As When We Started Living The Page Then After The Music Started Sounding.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Kapileswar-Moharana** [comment]
@Rakesh9100 Assign This Issue To Me Under SWOC

**Comment by Rakesh9100** [comment]
Proceed!! @Kapileswar-Moharana

**Comment by Rakesh9100** [comment]
@Kapileswar-Moharana PR status pls

**Comment by Rakesh9100** [comment]
@Kapileswar-Moharana Update of your PR pls

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana Update of your PR pls

Yes...

**Comment by Kapileswar-Moharana** [comment]
Hey @Rakesh9100 I Just Updated The Autoplay Restrictions Of Music To Start immediately page is Open And For Toggle The Sound Button I Changed The Sound Button Just Take A Look At This And Tell Me What Extra Changes you Want?
![Screenshot 2024-01-07 024540](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/129049677/e60654d8-a266-4dc5-8efe-906fadc0e8e1)
![Screenshot 2024-01-07 024500](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/129049677/a9aa3e05-5e4f-48d3-bdf8-c108e40525ea)
![Screenshot 2024-01-07 024519](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/129049677/9a8ed28a-8c06-4c13-ab80-608d76eef82c)

**Comment by Rakesh9100** [comment]
Let the instructions button be on left but sound, theme and back button should be on right only @Kapileswar-Moharana

**Comment by Kapileswar-Moharana** [comment]
> Let the instructions button be on left but sound, theme and back button should be on right only @Kapileswar-Moharana

ok Just A Minitue

**Comment by Rakesh9100** [comment]
Okay do fix and update me @Kapileswar-Moharana

**Comment by Kapileswar-Moharana** [comment]
> Okay do fix and update me @Kapileswar-Moharana

@Rakesh9100 Check Now Or Some Extra Changes You Want
