### ISSUE TITLE
Change Font and Background Color In According To functions

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [Rakesh9100/Click-The-Edible-Game#170]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I would Like To Update The  Font and Background Color In According To the functions Of The Webpage With Reponsiveness

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Kapileswar-Moharana** [comment]
@Rakesh9100 Assign This Issue To Me Under SWOC

**Comment by Rakesh9100** [comment]
Pls work on previously assigned issue first @Kapileswar-Moharana

**Comment by vrun1208** [comment]
@Rakesh9100 , Can you assign me to this issue?

**Comment by ankana007** [comment]
Please assign me this issue under SWoC S4.

**Comment by Rakesh9100** [comment]
The current UI is good. No change is required for now. Do work on other issues.
