### ISSUE TITLE
Back To Top Button In The Game Page

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [Rakesh9100/Click-The-Edible-Game#171]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I Would Like To Add The Back To Top Button In The Game Page

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Kapileswar-Moharana** [comment]
@Rakesh9100 Assign This Issue To Me Under SWOC

**Comment by Rakesh9100** [comment]
Proceed @Kapileswar-Moharana

**Comment by Kapileswar-Moharana** [comment]
Hey @Rakesh9100 Should I Add It In The Right Side Of The Nav Bar Section Or The Buttom Section... See The Below Screenshot n Say


![Screenshot 2024-01-05 013742](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/129049677/185fbb91-c12a-4bfe-93e8-e004151e9aaf)

**Comment by Rakesh9100** [comment]
### Button at the bottom right is fine.

### Pls do make it responsive as well.

![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/73993775/eb833cc4-31bd-4748-ae7c-a01b963b0c54)

![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/73993775/bcddbedd-8ad9-406c-bdfe-8c7ce62483a5)

![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/73993775/fc2d747a-b4ee-4a84-933d-c08d7b71d43d)

@Kapileswar-Moharana

**Comment by Kapileswar-Moharana** [comment]
@Rakesh9100 Ok By Tonight I Will fix it. Actually I Am at College placement drive
...

**Comment by Kapileswar-Moharana** [comment]
@Rakesh9100 Any Design That You Want Or This Design will ok...
![Screenshot 2024-01-07 144828](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/129049677/b01e9708-14d2-4256-bae9-e2deb564f831)

**Comment by Rakesh9100** [comment]
This will be fine, just update the colors and all according to UI @Kapileswar-Moharana
