### ISSUE TITLE
Change The UI Of Landing Page With Adjusting The Navbar Section

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [Rakesh9100/Click-The-Edible-Game#172]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I would Like To Update The  UI Of Landing Page With Adjusting The Navbar Section

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Kapileswar-Moharana** [comment]
@Rakesh9100 Assign This Issue To Me Under SWOC

**Comment by Rakesh9100** [comment]
Do you want to put navbar in the landing page? @Kapileswar-Moharana

**Comment by Kapileswar-Moharana** [comment]
@Rakesh9100 I would Like To Update The UI Of the Landing Page With Adjusting The Navbar Section Font And I con According To The Theme of Webpage

**Comment by Rakesh9100** [comment]
Provide the screenshots and details of what changes you would like to make @Kapileswar-Moharana

**Comment by Rakesh9100** [comment]
UI enhancement issue is already open, closing this issue.
