### ISSUE TITLE
Adjusting The No Of Bomb With Edible Icon

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [Rakesh9100/Click-The-Edible-Game#173]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I would Like To Adjust The number of Bomb With No of Edible Icon Because with Time The Edible Icon Are Generating More As Compared To Bomb

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Kapileswar-Moharana** [comment]
@Rakesh9100 Assign This Issue To me Under  SWOC

**Comment by krishnagitcontri** [comment]
Hi @sanketshinde3001 I would like to work on this issue can you please assign me

**Comment by Rakesh9100** [comment]
@Kapileswar-Moharana Proceed!!

**Comment by sanketshinde3001** [comment]
> Hi @sanketshinde3001 I would like to work on this issue can you please assign me

?

**Comment by Rakesh9100** [comment]
@Kapileswar-Moharana PR status
You are assigned to too many issues, do complete those before opening any new issue

**Comment by Rakesh9100** [comment]
@Kapileswar-Moharana Status of your PR

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana Status of your PR

@Rakesh9100 Sir Will Raise Al, Of Your PR By Today Then I will Go To sleep... Okk .... Codes Are Ready Just Let Me Finish One Branch Work... ...All Of This Project PR Will Raise Today...

**Comment by Rakesh9100** [comment]
Hey @Kapileswar-Moharana
You should not be irritated as it's your fault since you have opened multiple issues at once and you are already been assigned and given 4-5 days to work without providing any updates to me

**Comment by Kapileswar-Moharana** [comment]
> Hey @Kapileswar-Moharana You should not be irritated as it's your fault since you have opened multiple issues at once and you are already been assigned and given 4-5 days to work without providing any updates to me

@Rakesh9100 I Am not Irritating Sir, I'm Just Saying That I'm Trying To Finish All Of Your Issues Today..., Due To College Placement Work, I am Not Able To Give Time In The Day Time...Leave It I understand that I should Be Aware All About This... Before asking for an Assign Issue...

**Comment by Rakesh9100** [comment]
I can totally understand your placement situation which is first and foremost to be taken care.

That is why open 1-2 issues at a time, complete it and then go for another new issues from next time @Kapileswar-Moharana

**Comment by Kapileswar-Moharana** [comment]
> I can totally understand your placement situation which is first and foremost to be taken care.
> 
> That is why open 1-2 issues at a time, complete it and then go for another new issues from next time @Kapileswar-Moharana

@Rakesh9100 Ok Sir...
