### ISSUE TITLE
[BUG] : [Copyright year should be changed] 

### ISSUE THREAD

**Issue by SulagnaKundu** [Rakesh9100/Click-The-Edible-Game#174]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The copyright year should be 2024 instead of 2023.
I want to automate the copyright year, so that the year keeps on changing automatically every time.

### Screenshots

![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/103977344/41fdc68d-c79c-4c82-9660-3233c4632743)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by SulagnaKundu** [comment]
I want to work on this issue. Can you please assign me this issue under SWOC S4 ?

**Comment by Rakesh9100** [comment]
Proceed @SulagnaKundu Make sure to first pull the latest changes from the repo and then make your changes
