### ISSUE TITLE
Add pause menu

### ISSUE THREAD

**Issue by EmberTSeal** [Rakesh9100/Click-The-Edible-Game#18]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Once the game starts, there is no way to pause it.
I want to add a pause button to pause the game temporarily. 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by EmberTSeal** [comment]
I am a contributor under JWOC. Please assign this issue to me.

**Comment by Rakesh9100** [comment]
@EmberTSeal You are assigned this issue

**Comment by EmberTSeal** [comment]
Thank you!

**Comment by EmberTSeal** [comment]
Hi mentor, would you mind putting the Label (Easy/Medium/Hard) for this? It would give me a good idea about the time by which I should complete it. Thank you!

**Comment by Rakesh9100** [comment]
I am assigning the easy label, but it can be changed depending on the code quality. And you can work on, since there are no more mentees commented on this issue that they want to work. Hope you understand. @EmberTSeal

**Comment by EmberTSeal** [comment]
All right, thank you so much.
