### ISSUE TITLE
[Bug] Footer is overlapping with edible section components

### ISSUE THREAD

**Issue by KhushiRawat29** [Rakesh9100/Click-The-Edible-Game#180]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Destination:
1) Click "play the game:

Bug: The components of edible vegetable are overlapping with footer. If you scroll down, the problem persists with other components also.

### Screenshots

![2024-01-05](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/117963603/c87685a6-0884-4c34-ac0f-1d08a3466373)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by KhushiRawat29** [comment]
Here is how it will look like. If you like the change , please assign the issue to me. @Rakesh9100 

![2024-01-05 (1)](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/117963603/7092da12-346f-4516-9d08-041f5d84b818)

**Comment by Rakesh9100** [comment]
Proceed @KhushiRawat29

**Comment by KhushiRawat29** [comment]
Okay

**Comment by Rakesh9100** [comment]
Pls delete the package-lock.json file and also why there are changes in `index.html` file @KhushiRawat29
