### ISSUE TITLE
Enhancing the look of pause page

### ISSUE THREAD

**Issue by kamalsritha** [Rakesh9100/Click-The-Edible-Game#182]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I would like to change the styles of this so it becomes more attractive.

### Screenshots

<img width="1432" alt="Screenshot 2024-01-06 at 7 24 29 PM" src="https://github.com/Rakesh9100/Click-The-Edible-Game/assets/72294239/3723e062-ed18-4d5f-8b47-d5027d94db32">

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by kamalsritha** [comment]
@Rakesh9100 can you please assign me the above issue under SWOC.

**Comment by Rakesh9100** [comment]
Proceed @kamalsritha

**Comment by Aditi-Dahiya** [comment]
@kamalsritha , kindly provide update of your work.

**Comment by Rakesh9100** [comment]
@kamalsritha Provide the update of your work

**Comment by Shiv10122003** [comment]
Please assign it under iwoc

**Comment by Shiv10122003** [comment]
To me

**Comment by Rakesh9100** [comment]
Okay proceed @Shiv10122003

**Comment by Shiv10122003** [comment]
Thanks

**Comment by Ananyamishra08** [comment]
can you assign me this issue under jwoc

**Comment by Rakesh9100** [comment]
Issues for JWoC will be assigned from 15th Jan, 2024 @Ananyamishra08 

Till then keep exploring the projects!! ✨

**Comment by Shiv10122003** [comment]
#194 has been done
