### ISSUE TITLE
Option for user to toggle off/on sound

### ISSUE THREAD

**Issue by cryptocat8** [Rakesh9100/Click-The-Edible-Game#183]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

A need to add a sound button to toggle off/on all sound. I have worked on it, and I am a SWOC contributor.

### Screenshots

![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/62899717/9a86004e-42fc-4821-bfd4-6d6423e95052)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
This issue already exist. Pls  work on other issues @cryptocat8
