### ISSUE TITLE
Making a dark theme of the game and enhance the UI

### ISSUE THREAD

**Issue by kushaljgec2025** [Rakesh9100/Click-The-Edible-Game#19]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to enhance the UI and also want to add the dark theme in it

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigned @kushaljgec2025 Go ahead.

**Comment by kushaljgec2025** [comment]
Please add the tag easy medium or hard so that I can complete the task in time.

**Comment by Rakesh9100** [comment]
Done

**Comment by Code1705** [comment]
I also want ot contribute to this project under JWOC , please assign me.

**Comment by kushaljgec2025** [comment]
I am working on this @Rakesh9100 and will do pull request in evening.

**Comment by Rakesh9100** [comment]
No issues, Continue your work @kushaljgec2025
