### ISSUE TITLE
Adjust Styling for "Let's Get Started" Button in Instructions

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [Rakesh9100/Click-The-Edible-Game#190]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The "Let's get started!!" text in the instruction button is not fitting properly within the button, leading to a layout issue.

### Screenshots
![Screenshot from 2024-01-11 01-32-55](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/44281971/969dcaae-2daa-451f-9cfe-3a9e2fb3dfe1)

Assign this issue under SWoC

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by NaveenChandraAdhikari** [comment]
> Can you tell for which screen size this problem is appearing? @NaveenChandraAdhikari

for 1920*1080

**Comment by praptisharma28** [comment]
Assign me @NaveenChandraAdhikari under iwoc24. I can do this.

**Comment by sanskritisahu21** [comment]
I'm eager to contribute to Click-The edible- Game, and after exploring the issues, I'm interested in working on this issue please assign me this issue.

**Comment by Rakesh9100** [comment]
@NaveenChandraAdhikari You are assigned to too many issues, pls complete those first

@praptisharma28 Pls provide some more details what enhancements will you do?

**Comment by Dhairya1Gupta** [comment]
Please assign me this issue under IWOC @Rakesh9100 
There are quite few problems in this "Let's get Started" section 

1. The UI is not very eye catching.
2. Important details should be highlighted.
3. Font size and color can be more contrast to given background.
4. CSS animations can also be added in this section

**Comment by Rakesh9100** [comment]
Okay, proceed @praptisharma28

**Comment by praptisharma28** [comment]
Please add the difficulty level too @Rakesh9100

**Comment by Rakesh9100** [comment]
Difficulty level will be added by me based on the quality of the PR @praptisharma28 
So don't worry, just give your best and your score is in your hand!!

**Comment by shivam101203** [comment]
Please assign me this issue under IWOC @Rakesh9100
There are quite few problems in this "Let's get Started" section

    The UI is not very eye catching.
    Important details should be highlighted.
    Font size and color can be more contrast to given background.
    CSS animations can also be added in this section

**Comment by praptisharma28** [comment]
![Screenshot (487)](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/123169861/2db161bb-1243-432f-abe4-dbfe855e66ac)
 @Rakesh9100 , have a look please!

**Comment by praptisharma28** [comment]
@Rakesh9100 have a look at #199

**Comment by Rakesh9100** [comment]
Pls check the comment on the PR @praptisharma28

**Comment by Sakshamjain98** [comment]
Assign me @NaveenChandraAdhikari under iwoc24. I can do this.

**Comment by Sakshamjain98** [comment]
Please assign me this issue under IWOC @Rakesh9100
There are quite few problems in this "Let's get Started" section

The UI is not very eye catching.
Important details should be highlighted.
Font size and color can be more contrast to given background.
CSS animations can also be added in this section
