### ISSUE TITLE
Decrease the speed at which foods are appearing

### ISSUE THREAD

**Issue by thesri** [Rakesh9100/Click-The-Edible-Game#191]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The speed at which food apprearing is quite high compared to the bombs etc which is making it boring after some time
i can resolve this issue , kindly assign it to me under JWOC

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Shiv10122003** [comment]
Sir please add the label of iwoc

**Comment by Rakesh9100** [comment]
Issues for JWoC will be assigned from 15th Jan, 2024 @thesri 

Till then keep exploring the projects!! ✨

**Comment by Rakesh9100** [comment]
Do you want to work under IWOC @Shiv10122003

**Comment by Shiv10122003** [comment]
Yes sir please assign me thi issue

**Comment by Rakesh9100** [comment]
Okay proceed @Shiv10122003

**Comment by thesri** [comment]
Sir I asked first to assign this issue to me under jwoc so ain't it that I should get assigned ?

**Comment by Rakesh9100** [comment]
No, JWOC issue creation and assigning will start from 15th Jan @thesri

**Comment by thesri** [comment]
They said that we can raise issues but won't be assign till 15th

**Comment by Rakesh9100** [comment]
So you want to work under JWOC after 15th? @thesri

**Comment by thesri** [comment]
Yes

**Comment by Rakesh9100** [comment]
Okay, keeping this issue on hold @thesri

**Comment by Rakesh9100** [comment]
This issue is for JWoC program, you can open up new issues and get it assigned but don't work on this pls @Shiv10122003

**Comment by Sakshamjain98** [comment]
sir please assign me this issue under iwoc

**Comment by Rakesh9100** [comment]
You have to create this issue again after 15th Jan, as this is treated as invalid @thesri
