### ISSUE TITLE
Improving UI of the website

### ISSUE THREAD

**Issue by hemant933** [Rakesh9100/Click-The-Edible-Game#193]
### What's the style idea?

We need to improve UI for make it more pleasing.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by hemant933** [comment]
assign it to me plz

**Comment by Rakesh9100** [comment]
UI is quite good. Pls work on other issues @hemant933
