### ISSUE TITLE
The cursor is hanging

### ISSUE THREAD

**Issue by tushargupta1504** [Rakesh9100/Click-The-Edible-Game#196]
### What would you like to share?

cursor is hanging in it

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Edit the issue description and tick only that open source program for which you have opened the issue @tushargupta1504
