### ISSUE TITLE
Add a description to the game on the home page

### ISSUE THREAD

**Issue by subhashis2204** [Rakesh9100/Click-The-Edible-Game#2]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

# Objective
I felt the need for adding a brief description to the homepage of what the game is about.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
I think it's not needed since Play with your favorite edible is already a description @subhashis2204
