### ISSUE TITLE
[Style] Add transition for the instruction box

### ISSUE THREAD

**Issue by praptisharma28** [Rakesh9100/Click-The-Edible-Game#200]
### What's the style idea?

We need to improve the style/animation on the instruction box to make the UI good. Use transition for it.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by praptisharma28** [comment]
@Rakesh9100 , you can assign me, I will write the js for the button clicking and it will zoom out the box on 1st click and zoom in on the 2nd clcik.

**Comment by Rakesh9100** [comment]
Go ahead @praptisharma28

**Comment by shivam101203** [comment]
@Rakesh9100 sir please assign the issue to me.
i will add transition to it

**Comment by Rakesh9100** [comment]
@praptisharma28 Status of your PR pls

**Comment by praptisharma28** [comment]
@Rakesh9100 working on it, will give a PR by today.

**Comment by Rakesh9100** [comment]
@praptisharma28 Provide your PR

**Comment by Jenis07** [comment]
Can you assign me this issue under JWOC?

**Comment by Rakesh9100** [comment]
Go ahead @Jenis07

**Comment by Rakesh9100** [comment]
Status of your PR pls @Jenis07

**Comment by shivam101203** [comment]
Sir please assign me this issue under iwoc

**Comment by Rakesh9100** [comment]
Do you want to work @shivam101203

**Comment by shivam101203** [comment]
Yes sir I will please describe me what changes I have to do in instruction box

**Comment by praptisharma28** [comment]
@Rakesh9100 I opened this issue, I was midway doing it. Reassign me I will do a PR definitely by tomorrow. Wa busy with a hackathon.

**Comment by Rakesh9100** [comment]
Okay proceed @praptisharma28 

Pls wait till tomorrow, if not done then you will be assigned @shivam101203

**Comment by Rakesh9100** [comment]
@praptisharma28 Provide your PR

**Comment by praptisharma28** [comment]
@Rakesh9100 the css is overlapping, you can assign to some other.

**Comment by shivam101203** [comment]
Please assign this issue to me under iwoc @Rakesh9100

**Comment by Rakesh9100** [comment]
Proceed @shivam101203

**Comment by Rakesh9100** [comment]
PR status pls @shivam101203

**Comment by shivam101203** [comment]
Sir I will do it by today please sir

**Comment by antilneeraj** [comment]
@Rakesh9100 please assign this issue to me under JWOC

**Comment by Rakesh9100** [comment]
Proceed @antilneeraj

**Comment by Rakesh9100** [comment]
Status of your PR pls @antilneeraj

**Comment by antilneeraj** [comment]
I'll push it by tomorrow

**Comment by antilneeraj** [comment]
Just some minor adjustments are left
