### ISSUE TITLE
[Feature] Pause/restart, high score and gameplay boxes enhancement

### ISSUE THREAD

**Issue by praptisharma28** [Rakesh9100/Click-The-Edible-Game#202]
### Description

 Contrasting the pause/restart box, high score box and gameplay box with the instruction box as the UI for them need beautification too.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by praptisharma28** [comment]
@Rakesh9100 , assign me will do the same for all these boxes too and then update the readme accordingly,

**Comment by praptisharma28** [comment]
@Rakesh9100 , have a look at these. I'll do the PR if you like them. You can assgn me too. Now they matches the UI of the new instruction box I made, all these boxes have gradient and animation too. And I will add these screenshots in the readme too so that we can close that issue also.
![Screenshot (494)](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/123169861/d1ed50fb-8d97-4fa4-8d9b-be796f1f6487)
![Screenshot (497)](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/123169861/1273218d-fb74-4c9d-bb05-cdcd7fac85ac)
![Screenshot (496)](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/123169861/4516fd00-8d58-43d4-938e-8ecdcec05409)

**Comment by Rakesh9100** [comment]
This yellow seems to be very dominating. Can you make it little light or use some good different combination @praptisharma28

**Comment by praptisharma28** [comment]
Ok @Rakesh9100 , let me try a green or may be purple gradient.

**Comment by praptisharma28** [comment]
![Screenshot (498)](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/123169861/c803b94d-7640-4d8f-9714-650aa7683f04)
@Rakesh9100

**Comment by Rakesh9100** [comment]
FIrst one seems nice @praptisharma28

**Comment by praptisharma28** [comment]
https://github.com/Rakesh9100/Click-The-Edible-Game/pull/207 Review the PR @Rakesh9100 , please add the difficulty level and iwoc24 tag before merging.

**Comment by praptisharma28** [comment]
I need to sync fork, for a previous PR of someone you previously merged. I synced, needed to doscard commits for that, doing fresh commits again in the same PR. @Rakesh9100

**Comment by praptisharma28** [comment]
https://github.com/Rakesh9100/Click-The-Edible-Game/pull/208 check @Rakesh9100 
Everything is fine from my side, regarding high score, current score etc.
![Screenshot (512)](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/123169861/fd889062-5e53-4a0e-b277-fa2003adf254)
