### ISSUE TITLE
[Bug] Cursor Issue in Website Game

### ISSUE THREAD

**Issue by Tholkappiar** [Rakesh9100/Click-The-Edible-Game#203]
## Problem Description

In the website's game section, a cursor inconsistency issue has been identified. The game utilizes a circular cursor, but for specific options, the arrow cursor is displayed upon hover. This results in a situation where two different cursors are visible on certain buttons, leading to a less-than-optimal user experience.

## Reproduction Steps

1. Launch the website and navigate to the game section.
2. Observe the circular cursor while interacting with the game.
3. Hove the cursor on the sound and theme change options , Identify specific options or buttons where the cursor unexpectedly changes to the arrow cursor upon hover.

## Expected Behavior

The cursor should consistently remain as the circular cursor throughout the game, providing a cohesive and immersive user experience.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by hemant933** [comment]
assign it to me plz

**Comment by Rakesh9100** [comment]
Go ahead @Tholkappiar
