### ISSUE TITLE
Change in the button style

### ISSUE THREAD

**Issue by riyatyag-6** [Rakesh9100/Click-The-Edible-Game#206]
### What's the style idea?

We need to improve the style of button by adding css or bootstrap element.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Which button are you talking about? @riyatyag-6

**Comment by subh03** [comment]
I would like to work on this issue under JWOC
