### ISSUE TITLE
Home/menu page changes 

### ISSUE THREAD

**Issue by vishwajeetfate** [Rakesh9100/Click-The-Edible-Game#209]
### What's the style idea?

![changes](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/110755446/8739f42c-147b-4c2b-b934-1fca0c4a52e2)
please assign it to me !
@Rakesh9100 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
No need. Pls work on other issues @vishwajeetfate
