### ISSUE TITLE
Remove the home button just from the homepage

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/Click-The-Edible-Game#21]
![Screenshot 2023-02-15 204038](https://user-images.githubusercontent.com/73993775/219068509-4ee16c90-8692-4375-8ed6-ec4ca3e6d506.png)

<h3>The home button should appear after we click the Play Game button and head to the next page.

**Comment by utkarsh006** [comment]
@Rakesh9100 Assign this issue to me under JWOC.

**Comment by Rakesh9100** [comment]
Assigned @utkarsh006 to you

**Comment by AimanSh123** [comment]
I want to work on this issue under JWOC so please assign it to me
