### ISSUE TITLE
[Bug] Responsiveness of the instruction box

### ISSUE THREAD

**Issue by shivam101203** [Rakesh9100/Click-The-Edible-Game#210]
### Description

The lets get started button is not shown properly and it is not clear from the view of the screen shot.

### Screenshots

![Screenshot from 2024-01-15 22-26-50](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/156535575/538cbdc0-8321-46c0-bb50-b8ec251163d0)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by shivam101203** [comment]
please assign this issue to me under iwoc2024 @Rakesh9100 .

**Comment by shivam101203** [comment]
@Rakesh9100 please reply fast

**Comment by Rakesh9100** [comment]
Will you make every instruction box responsive @shivam101203

**Comment by shivam101203** [comment]
Okkk

**Comment by shivam101203** [comment]
I will made it responsive as well

**Comment by Rakesh9100** [comment]
Okay proceed @shivam101203

**Comment by shivam101203** [comment]
Thanks sir

**Comment by Lavanya-Sathya** [comment]
Hey @Rakesh9100 , I would like to contribute to this issue. Please assign this to me

**Comment by Rakesh9100** [comment]
You want to work for which open source program, pls make the proper comment @Lavanya-Sathya

**Comment by Lavanya-Sathya** [comment]
@Rakesh9100 , Assign it under JWOC

**Comment by Rakesh9100** [comment]
Go ahead @Lavanya-Sathya
