### ISSUE TITLE
[Feature] Adding a Logo

### ISSUE THREAD

**Issue by mansi1309** [Rakesh9100/Click-The-Edible-Game#215]
### Description

I would like to add logo in header section .Please assign this issue to me.

### Screenshots

![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/133951716/c0c11fbd-519f-4e43-ae9c-8b958628432a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Which logo you want to add @mansi1309

**Comment by mansi1309** [comment]
I want to add logo of beautify on the top right corner side .Someting like
logo used in favicon .It looks good with logo .

**Comment by Rakesh9100** [comment]
No need. Pls work on issues assigned to you in my other projects @mansi1309
