### ISSUE TITLE
[Style] Changing the cursor format

### ISSUE THREAD

**Issue by Utkarsht2310** [Rakesh9100/Click-The-Edible-Game#217]
### What's the style idea?

The present cursor is slow and not too good according to the game it require other type which look better then the the circle one so the user can feel the game like real grabbing experience by changing the circle to Hand(✋) Type mouse cursor which increase user experience.
I want to work on this so please assign this issue to me under JWOC'2024 .
Thank You!

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Utkarsht2310

**Comment by Rakesh9100** [comment]
Status of your PR pls @Utkarsht2310

**Comment by vishapraj** [comment]
pls assign me this issue under 'JWOC'

**Comment by Rakesh9100** [comment]
Are you working @Utkarsht2310
