### ISSUE TITLE
[Feature] Add a Drag & Drop Feature and Redesign of the Upload Section

### ISSUE THREAD

**Issue by antilneeraj** [Rakesh9100/Click-The-Edible-Game#219]
### Description

- I'll redesign the Image upload Area to look more modern. 
- Add a handy drag-and-drop feature for a smoother experience.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by antilneeraj** [comment]
@Rakesh9100  Kindly assign this issue to me under JWOC.

**Comment by Rakesh9100** [comment]
Proceed @antilneeraj
