### ISSUE TITLE
Redesign the footer

### ISSUE THREAD

**Issue by debuuuu007** [Rakesh9100/Click-The-Edible-Game#220]
### What's the style idea?

I will make the footer into a professional and good looking one.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What idea you have to enhance the footer as current one is fine @debuuuu007
