### ISSUE TITLE
[Style]: Changing font and style of text 

### ISSUE THREAD

**Issue by Ishita928** [Rakesh9100/Click-The-Edible-Game#222]
### What's the style idea?

We need to improve:
font and style of the text above images and image bar can be modified to make it look more appealing

![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/146575485/1a67e78c-d99a-4c9b-96e5-cb49206b4c53)
![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/146575485/675a0646-8d47-4dd2-877c-715c12603912)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by arnvsnigi** [comment]
![Screenshot 2024-01-22 at 10 03 05 PM](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/22290716/22a61e4c-70b2-47c0-a34a-fab5a4e5157f)

Hey I am Arnav..
How does this look....Can u assign me to the issue for IWOC24

**Comment by arnvsnigi** [comment]
> ![Screenshot 2024-01-22 at 10 03 05 PM](https://private-user-images.githubusercontent.com/22290716/298655481-22a61e4c-70b2-47c0-a34a-fab5a4e5157f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NDE1MjAsIm5iZiI6MTcwNTk0MTIyMCwicGF0aCI6Ii8yMjI5MDcxNi8yOTg2NTU0ODEtMjJhNjFlNGMtNzBiMi00N2MwLWEzNGEtZmFiNWE0ZTUxNTdmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDE2MzM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlN2RmMTQ0MzhlNTBjMGEzMDU4MjhhODMyM2UwNTZkYThhOWMzODdkNjliNzY1OWNiNTQ5ZmRiODExOGNmNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.teT1kStqzQNiv0Ob6_N-FOOGqC1_dJUfcPSe7GgxKM8)
> 
> Hey I am Arnav.. How does this look....Can u assign me to the issue for IWOC24

Added some shadows,changed the color scheme as well as font face

**Comment by arnvsnigi** [comment]
oh.. its not under IWOC..

**Comment by Rakesh9100** [comment]
![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/73993775/87c985c9-128e-47c2-854c-6b3d4ab70150)

Font is already fine, pls work on other issues @Ishita928
