### ISSUE TITLE
[Style] Add logo on navbar

### ISSUE THREAD

**Issue by Ishita928** [Rakesh9100/Click-The-Edible-Game#223]
### What's the style idea?

We need to improve:
a relevant logo can be added at top left corner of the navbar
![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/146575485/77c6f9c9-8f45-4e32-8269-dc47f693faa4)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by SharmaDhruv2511** [comment]
I want to work on this issue Can you please assign it to me? Can i select both JWOC as well as SWOC ? @Ishita928

**Comment by Rakesh9100** [comment]
Which logo you want to add @Ishita928

**Comment by Ishita928** [comment]
any logo that matches your game title and description ,like;
![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/146575485/8a3e9a76-b83b-43de-a4df-2e3cf7d783b6)

i have made this logo ,if you want me to make changes ,please suggest ! thanks

**Comment by Rakesh9100** [comment]
Can you include this icon in the favicon as well @Ishita928

**Comment by Ishita928** [comment]
In favicon an icon is already present and this logo is quite large for favicon icon but if u want i can try.

**Comment by Rakesh9100** [comment]
Yes, favicon is present but navbar icon and favicon should be same or similar. So you can think of some different icon which fits at both the places @Ishita928

**Comment by Ishita928** [comment]
![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/146575485/f477648b-f001-4114-b3d9-6cffb7cb697f)
 
can we make favicon like this and navbar icon as mentioned in the initial image

**Comment by Rakesh9100** [comment]
Yes, you can but make sure favicon should be clear @Ishita928

**Comment by Rakesh9100** [comment]
Status of your PR pls @Ishita928

**Comment by Ishita928** [comment]
![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/146575485/341ca6f8-d830-4f2f-a46e-429269f86845)
I changed the style of the logo to improve its design ,pls review it

**Comment by Ishita928** [comment]
favicon will look like this , as it is not possible to keep the entire logo clearly visible in such small size so i made it like this
![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/146575485/f51f5c22-2d09-41f3-8f5a-8ef15bc9df16)

**Comment by Rakesh9100** [comment]
Logo looks good and favicon also seems fine @Ishita928

**Comment by Ishita928** [comment]
![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/146575485/50d9df78-e824-49d4-b6af-cb5ce17ad44c)


Is this fine?

**Comment by Rakesh9100** [comment]
I suppose make the size little small so that it don't exceeds the navbar on the next page when we are scrolling to select any edible @Ishita928

**Comment by Ishita928** [comment]
![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/146575485/3089bd66-9729-4a13-a0a1-58433b504b62)
Now ,is it fine ?

**Comment by Rakesh9100** [comment]
Create your PR, I will check in the deploy preview @Ishita928
