### ISSUE TITLE
[Feature] Add a Star rating system

### ISSUE THREAD

**Issue by Sneha6003** [Rakesh9100/Click-The-Edible-Game#226]
### Description

I would like to add a star rating system for the users to rate their experience.
The icon would be present in the footer of the webpage, which upon clicking will navigate to the star rating page.
I am attaching some screenshots for better understanding.

I would like to work on this issue under JWOC.
Thank you 

### Screenshots

![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/147996970/87047a70-024d-44ba-b446-7f88ec3e2ade)

![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/147996970/c851e14e-7d56-4591-a570-be98ae5b97e4)

![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/147996970/aa28783f-e90c-4c9e-9b6c-5e6ca2cde99d)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Sneha6003

**Comment by ayann07** [comment]
Please assign me this

**Comment by Rakesh9100** [comment]
Pls brief how you will solve this issue and for which open source program @ayann07

**Comment by ayann07** [comment]
I will implement like sneha did and I will be working under swoc 2024.

**Comment by Rakesh9100** [comment]
Okay proceed and use your own idea and make it more better @ayann07

**Comment by Rakesh9100** [comment]
Status of your PR @ayann07

**Comment by ayann07** [comment]
I will be creating the pr within 2 days
