### ISSUE TITLE
I will add responsive footer and navbar

### ISSUE THREAD

**Issue by Zenitssuu** [Rakesh9100/Click-The-Edible-Game#227]
### Description

I will create responsive navbar and footer, this website have no navbar and footer yet, so I want to contribute on it under JWOC'24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
It is already present. Pls work on other good issues @Zenitssuu

**Comment by Zenitssuu** [comment]
May I know why you closed this issue?
