### ISSUE TITLE
[Docs] Add Project Local Installation Video to README

### ISSUE THREAD

**Issue by rahat2134** [Rakesh9100/Click-The-Edible-Game#228]
### Category of documentation update

Contributor onboarding could be improved by providing a visual guide on how to install the project locally. Adding a video demonstration will help newcomers understand the setup process more effectively.

### Describe the change you think might work

Proposed Content:
A short video covering the following:

Cloning the repository.
Installing dependencies.
Configuring any necessary settings.
Running the project locally.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by rahat2134** [comment]
@Rakesh9100 assign this issue to me under JWoC

**Comment by Rakesh9100** [comment]
Proceed @rahat2134

**Comment by rahat2134** [comment]
@Rakesh9100 can the difficulty be changed to hard if possible. Thank you.(It took quite much time)
