### ISSUE TITLE
[Feature] A feedback form about the game

### ISSUE THREAD

**Issue by thesri** [Rakesh9100/Click-The-Edible-Game#234]
### Description

A feed back form about the game which will let us know their experience  and what to improve. please assign this issue under jwoc 2024

### Screenshots

![Uploading Screenshot 2024-01-23 173136.png…]()

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue is already open for this @thesri
