### ISSUE TITLE
[Bug] Image upload format issue

### ISSUE THREAD

**Issue by rajpootjyoti700** [Rakesh9100/Click-The-Edible-Game#237]
### Description

on upload image section of click the edible game 
if a transparent image is required we can make sure to allow only png format images as jpegs do not support background transparency

I propose to change the allowed format of uploaded image to png and mention it on the frontend as well, that user has to upload png only

### Screenshots

![WhatsApp Image 2024-01-26 at 23 31 58](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/133164017/479fb897-dfcc-4189-b869-90f50985369d)
![WhatsApp Image 2024-01-26 at 23 30 41](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/133164017/4730a47e-3772-40b6-9662-67c7cf90f35d)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by rajpootjyoti700** [comment]
i want to work on this issue plz assign it to me

**Comment by Rakesh9100** [comment]
Proceed @rajpootjyoti700

**Comment by Rakesh9100** [comment]
Pls provide your PR by today else you will be unassigned @rajpootjyoti700

**Comment by rajpootjyoti700** [comment]
sry for delay give me 1 or days will update

**Comment by rajpootjyoti700** [comment]
fixed my issue plz check it
