### ISSUE TITLE
[Bug] Redirecting to the Game Screen

### ISSUE THREAD

**Issue by antilneeraj** [Rakesh9100/Click-The-Edible-Game#239]
### Description

When Clicked on any of the Edible we are not able to proceed to play the game. I would like to fix this issue.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by antilneeraj** [comment]
@Rakesh9100 Kindly assign this issue to me under JWOC. So, that I can fix it as soon as possible.

**Comment by Rakesh9100** [comment]
Proceed @antilneeraj
