### ISSUE TITLE
To Enhance style of landing page

### ISSUE THREAD

**Issue by VIDHISHAK15** [Rakesh9100/Click-The-Edible-Game#241]
### What's the style idea?

We need to improve the font and background of landing page 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
No need. Pls work on other issues @VIDHISHAK15
