### ISSUE TITLE
[Feature] Easy/Medium/Hard Level Selection

### ISSUE THREAD

**Issue by Surajit0573** [Rakesh9100/Click-The-Edible-Game#244]
### Description

I would like to add a new feature to the game. Players should have the option to choose between three difficulty levels, easy, medium, and hard, before they start playing.

 This option should be available after they have selected the food they want to play with.

 In the easy level, the number of bombs and rotten ingredients will be less, and as the difficulty level increases, the number of bombs and rotten ingredients will increase accordingly.

### Screenshots

Level selection options will be given in this page only.

![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/111490250/408d63f2-dc7b-4652-961e-5a59b7ddf1bc)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Surajit0573
