### ISSUE TITLE
Add contributors section in Readme file

### ISSUE THREAD

**Issue by Arbtrage** [Rakesh9100/Click-The-Edible-Game#25]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add a contributors section in the readme file where it would show all the contributors.
@Rakesh9100 , please assign me this issue.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigning to you @Arbtrage
