### ISSUE TITLE
Image Upload Issue [Better Solution]

### ISSUE THREAD

**Issue by whonehuljain** [Rakesh9100/Click-The-Edible-Game#250]
### Description

In the image upload section, when the image is uploaded, it needs to be transparent, but not all people have a transparent image of that edible whose photo they would like to upload. So what I propose is that we could add an inbuilt cropper in the website and also, we can on our side remove the background of that image.
We could do this by using the cropper.js library, and by using remove.bg api.
Please assign this issue to me. I would love to contribute and learn with the community.
Thank You! 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Upload section only allows PNG image and so the background would be transparent for almost every images @whonehuljain
