### ISSUE TITLE
[Style] Improve the UI of dark mode

### ISSUE THREAD

**Issue by Sanglap-Halder** [Rakesh9100/Click-The-Edible-Game#256]
### What's the style idea?

We need to improve the color combination of the website on dark mode.
I want to do the task under JWoC 2024

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
No need. Pls work on other good issues @Sanglap-Halder
