### ISSUE TITLE
Navigation bar and footer

### ISSUE THREAD

**Issue by kinjalchawla123** [Rakesh9100/Click-The-Edible-Game#258]
### What's the style idea?

We need to improve the UI of the navigation bar and footer. Assign me this issue as i can improve this under swoc24
@rakesh

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
No need of improvement now. Pls work on other good issues @kinjalchawla123

**Comment by kinjalchawla123** [comment]
Suggest me something I can work upon your site.
I was having my first sem exams due to which I wasn't active.
Please suggest something.
