### ISSUE TITLE
[Style] Modify the box design

### ISSUE THREAD

**Issue by Gauranshgoel123** [Rakesh9100/Click-The-Edible-Game#261]
### What's the style idea?

currently it gives a trippy look for the user
![image](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/121503835/cb93d027-0a3e-4493-b533-eb8eddd931cf)
The CSS for it can be improved in a more elegant manner!

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Gauranshgoel123** [comment]
the current deployed website has an animation in it which can be improvised to remove the trippy effect for the user

**Comment by Rakesh9100** [comment]
What improvements exactly you want to do and to the cards or animations?

**Comment by Rakesh9100** [comment]
What improvements exactly you want to do and to the box or animations? @Gauranshgoel123

**Comment by Gauranshgoel123** [comment]
i meant both to the box as well as the animations
both's CSS can be changed
unique features like hover,glassmorphisms can be added
i'll look into more features that can be added except these once I'm assigned this issue

**Comment by Rakesh9100** [comment]
Okay go ahead, will see @Gauranshgoel123
