### ISSUE TITLE
[Style] Fix the visibility of the instruction box

### ISSUE THREAD

**Issue by arjunmishraaa** [Rakesh9100/Click-The-Edible-Game#263]
### What's the style idea?

We need to improve the instruction page its not fully visible in chrome tab but visible in full display, improving this will lead to enhance the UX
![Screenshot 2024-12-12 232813](https://github.com/user-attachments/assets/009b8afd-a842-416d-b207-b566123d028d)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by arjunmishraaa** [comment]
@Rakesh9100 assign this issue to me

**Comment by Rakesh9100** [comment]
Are you working for any open source program or just for self contribution @arjunmishraaa

**Comment by arjunmishraaa** [comment]
@Rakesh9100 I'm currently contributing to open source through the SWOC

**Comment by arjunmishraaa** [comment]
@Rakesh9100 the proper instructions are not visible in the browser tab but are visible in full-screen mode. Kindly refer to the attached picture in issue for further clarification

**Comment by Rakesh9100** [comment]
SWOC contribution begins on 1st Jan 2025 and this project will not be part of that, still, if you want to fix the issue now, you can @arjunmishraaa

**Comment by arjunmishraaa** [comment]
@Rakesh9100 Sure!!
