### ISSUE TITLE
Fix the restart button not working

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/Click-The-Edible-Game#27]
![1](https://user-images.githubusercontent.com/73993775/219271984-c5b1a470-f902-46e2-a20c-f1fc2e32cc09.png)

**Comment by EmberTSeal** [comment]
I would like to work on this issue under JWOC.

**Comment by Laxmankohar** [comment]
Hey @Rakesh9100 , I would like to work on this issue uder JWOC. Can you please assign it to me?

**Comment by Rakesh9100** [comment]
@EmberTSeal You are assigned

**Comment by Rakesh9100** [comment]
@Laxmankohar The first one whi comments is assigned the issue, if he/she fails then next one will be assigned
