### ISSUE TITLE
A scroll down should be added 

### ISSUE THREAD

**Issue by Ritu-2001** [Rakesh9100/Click-The-Edible-Game#29]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

i want to add a scroll down 

### Screenshots

at this time i have no screenshot

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
You don't have SS fine but provide any reference what will you do it's not clear @Ritu-2001

**Comment by Ritu-2001** [comment]
i want to add an another  edible section  and after that i will a scroll to down and up the whole page

**Comment by Ritu-2001** [comment]
ok

**Comment by SarveshGholap** [comment]
I want to work on this issue under jwoc

**Comment by Rakesh9100** [comment]
@Ritu-2001 Status of your work

**Comment by deepbeatz** [comment]
I want to work on this under JWOC

**Comment by Ritu-2001** [comment]
@Rakesh9100 
![Screenshot (166)](https://user-images.githubusercontent.com/100128956/219923947-af3508e6-93d0-4438-8c58-c92d95d8a779.png)

**Comment by Ritu-2001** [comment]
@Rakesh9100 add a section of favorite snacks items  only i have to add a scroll bar

**Comment by Rakesh9100** [comment]
Yes, fine make it. @Ritu-2001

**Comment by Rakesh9100** [comment]
@SarveshGholap Do you want to work ?

**Comment by Rakesh9100** [comment]
@deepbeatz Do you want to work ?

**Comment by deepbeatz** [comment]
I want to, but can u pls explain me what was his/her motto in this issue, he/she just tried to make a scroll bar right??

**Comment by Rakesh9100** [comment]
Yes, in the page of selecting an edible, while adding more categories of edibles, they went in disorder like some went to previous screen and some to next screen, so add a scroll bar so that more categories can be added in the same screen without affecting the gameplay @deepbeatz

**Comment by deepbeatz** [comment]
i have loaded the project and using live-server of vscode i am viewing the site......there are only 2 sections of edibles that i can see, fruits and vegetables.......... and there is already a scroll bar..........what do i do now? @Rakesh9100

**Comment by Rakesh9100** [comment]
Let's say you added two more sections, such as chocolates and snacks, then see what happens to those. They will go to the previous page and next gameplay screen page, so to prevent this add a side scrollbar through which player and scroll and select different edible on the same screen.

**Comment by Hritik1503** [comment]
I want to work on this under JWOC . I will work with you previously on add footer issue. so please assign me this task

**Comment by Rakesh9100** [comment]
@deepbeatz Are you working ? Then will assign or pass to next mentee

**Comment by deepbeatz** [comment]
I am working sir

**Comment by Rakesh9100** [comment]
> I am working sir

Ok Ok continue.

**Comment by Rakesh9100** [comment]
> I am working sir

Okay continue, just confirming @deepbeatz

**Comment by manya0210** [comment]
Hello sir...I want to work on this issue under jwoc...

**Comment by Rakesh9100** [comment]
Provide the status of your PR @deepbeatz

**Comment by deepbeatz** [comment]
I am having some problems sir.....and that's why i tried to reach you on discord.....plz check

**Comment by Rakesh9100** [comment]
@Hritik1503 Do you want to work ?

**Comment by Rakesh9100** [comment]
@manya0210 Do you want to work on this ?

**Comment by manya0210** [comment]
Yes sir ...I want to work on this issue

**Comment by Rakesh9100** [comment]
Assigned to you @manya0210

**Comment by Rakesh9100** [comment]
@manya0210 Status of your PR

**Comment by Hrx4** [comment]
Hey @Rakesh9100  so in this issue i have to add more options like snacks , chocolates and make a scroll down right?

**Comment by Rakesh9100** [comment]
Yes @Hrx4

**Comment by Hrx4** [comment]
ok then assign me the issue under JWOC

**Comment by ManasaKaza** [comment]
I want to work on this issue under JWOC

**Comment by Rakesh9100** [comment]
Do you want to work @ManasaKaza

**Comment by Rakesh9100** [comment]
@Hrx4 Status of your work

**Comment by Rakesh9100** [comment]
Do you want to work @ManasaKaza

**Comment by ManasaKaza** [comment]
Yes..

**Comment by Rakesh9100** [comment]
Start working @ManasaKaza

**Comment by Rakesh9100** [comment]
Make sure to complete the work or update if unable to complete @ManasaKaza

**Comment by ManasaKaza** [comment]
Yeah sure

**Comment by ManasaKaza** [comment]
How many days do I have to complete this ..??
Actually tomorrow phase 1 ends right
So should I complete it by tomorrow?

**Comment by Rakesh9100** [comment]
Try to make PR by end of phase 1 @ManasaKaza

**Comment by ManasaKaza** [comment]
I suddenly had to go out of station so I can't make PR by the end of phase 1

**Comment by Rakesh9100** [comment]
Have you understood the issue properly and will surely work ? @ManasaKaza

**Comment by ManasaKaza** [comment]
Yeah I will surely work and understood the issue but I can't Make a PR by the end of phase 1

**Comment by Rakesh9100** [comment]
Okay, you are allowed to make PR by end of 6th march @ManasaKaza If acceptable then reply otherwise, will pass to other mentee.

**Comment by ManasaKaza** [comment]
I'm sorry, you can pass it to the other

**Comment by vk20july** [comment]
I want to work on this issue under JWOC

**Comment by Rakesh9100** [comment]
Okay, if it remains incomplete then you can again comment on this @ManasaKaza

**Comment by Rakesh9100** [comment]
Assigning to you @vk20july

**Comment by Rakesh9100** [comment]
Assigned to you @vk20july Start working

**Comment by vk20july** [comment]
@Rakesh9100  sorry sir just now the date sheet of my mid sem has come I wont't be able to do this task

**Comment by Rakesh9100** [comment]
Okay no issues, good that you informed earlier. @vk20july

**Comment by ritika728** [comment]
Hey @Rakesh9100, I would like to work on this issue

**Comment by Rakesh9100** [comment]
Assigning to you @ritika728, Start working
