### ISSUE TITLE
Add/Improve hover effect on "Play Game" button.

### ISSUE THREAD

**Issue by RathoreAbhiii** [Rakesh9100/Click-The-Edible-Game#3]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

After going through the website, I found the design of the "Play Game" button very simple and would like to work on improving its css.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by RathoreAbhiii** [comment]
@Rakesh9100 Could you please assign this issue to me? Thanks!

**Comment by Rakesh9100** [comment]
Okay proceed but make sure to make it really designed and attractive. @RathoreAbhiii

**Comment by RathoreAbhiii** [comment]
Yeah sure, but please assign me this issue!

**Comment by Rakesh9100** [comment]
Done !!

**Comment by RathoreAbhiii** [comment]
@Rakesh9100 Please add the "hacktoberfest" title to this issue/PR before merging it. Also, please see that the gif is a bit laggy, the same is not the case on the actual website. Had a great time working on this issue. Thanks!

**Comment by Rakesh9100** [comment]
> @Rakesh9100 Please add the "hacktoberfest" title to this issue/PR before merging it. Also, please see that the gif is a bit laggy, the same is not the case on the actual website. Had a great time working on this issue. Thanks!

Okay done.
