### ISSUE TITLE
Add the feature to pause the game by space bar

### ISSUE THREAD

**Issue by D3vilGhost** [Rakesh9100/Click-The-Edible-Game#32]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hi!
myself Kartikey Agarwal JWoC'23 contributor.
i want to work or fix the thing that pause button only works when clicked via mouse but it will be better if player could pause the game by space bar key while playing the game.
i wish to work on this issue.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead @D3vilGhost

**Comment by D3vilGhost** [comment]
Thank you sir!

**Comment by manya0210** [comment]
Hello sir...I want to work on this issue under jwoc
