### ISSUE TITLE
Back or Home button

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/Click-The-Edible-Game#33]
<h3>Remove the down right corner home button.</h3>

![Screenshot 2023-02-17 000432](https://user-images.githubusercontent.com/73993775/219477030-6f4d18cd-2832-42a0-b4c0-36e440781fce.png)

<h3>And implement a well-designed mini back button at this page which would take to the homepage.</h3>

![2](https://user-images.githubusercontent.com/73993775/219477413-976397b1-07a8-427e-be9c-d55b4968079c.png)

Note:- The back button should only be present and visible in the selection of edible page(2nd page), not the home or first page.

**Comment by AK-shat-JAIN** [comment]
I want to do that

**Comment by AK-shat-JAIN** [comment]
under JWOC

**Comment by Rakesh9100** [comment]
Okay assigned @AK-shat-JAIN

**Comment by AK-shat-JAIN** [comment]
I have generated A PR regarding this
