### ISSUE TITLE
Adding animation to Landing Page 

### ISSUE THREAD

**Issue by AK-shat-JAIN** [Rakesh9100/Click-The-Edible-Game#34]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Landing page looks very normalistic
Want to add animation effect in it such that the text "Play with your Favorite Edible🎮" will animate and come like in this website 
https://ak-shat-jain.github.io/FoodGenix/
that's also created by me

JWOC mentee

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
One issue is already assigned to you, first do complete that @AK-shat-JAIN

**Comment by AK-shat-JAIN** [comment]
Sure @Rakesh9100 than please assign this task to me I have a great idea

**Comment by AK-shat-JAIN** [comment]
Till then please add tags to this one

**Comment by Rakesh9100** [comment]
Okay will do if you complete the assigned issue ASAP. Then only I can assign you this @AK-shat-JAIN

**Comment by AK-shat-JAIN** [comment]
Hello sr for this update
I want to ask some doubts

**Comment by Rakesh9100** [comment]
Yes do ask

**Comment by AK-shat-JAIN** [comment]
can I make Animation on same home page above Play Game Button 
or I have some other idea too
Make 3 separate page landing.html landing.css and landing.css such that after animation we will be redirected to home page after about 5sec (animation time)

**Comment by Rakesh9100** [comment]
I would suggest the second idea, which will look more good. But at the same time, you should make the changes in which you are comfortable and accordingly difficulty of PR will be tagged. Hope you understand.

**Comment by AK-shat-JAIN** [comment]
Also sr then website should be live from the landing page (which shifts to home automatically)

**Comment by Rakesh9100** [comment]
Yes I understood. Go ahead if it will be attractive for the project. And remember to update your codebase first, otherwise conflict will occur.

**Comment by AK-shat-JAIN** [comment]
Yes sr 
I am beginning to work on it now

**Comment by AK-shat-JAIN** [comment]
Hlo sir please comment on Font and anything 
as if you say its ok than I move forward with it

![image](https://user-images.githubusercontent.com/84455686/219800243-fde4e34d-3cae-4c35-9a62-a67cba848cef.png)

**Comment by AK-shat-JAIN** [comment]
Created PR please review it

**Comment by AK-shat-JAIN** [comment]
Thank You 🤩❤️‍🔥❤️‍🔥
Hope to see more issue and merge more PRs

**Comment by Rakesh9100** [comment]
Yes, Keep Contributing. Good Luck 🎊
