### ISSUE TITLE
Update readme 

### ISSUE THREAD

**Issue by Akanksha-Sen** [Rakesh9100/Click-The-Edible-Game#35]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to update readme by enhancing the language.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Code1705** [comment]
I definately want to contribute to the project by writing a proper readme file with detailed info about the game and its features, please assign me under JWOC.

**Comment by Rakesh9100** [comment]
What exactly do you want to update? Can you provide any reference since everything is well updated as per me. @Akanksha-Sen

**Comment by dew-coder** [comment]
Please assign me this issue under JWOC

**Comment by Rakesh9100** [comment]
@Code1705 What you want update? Pls specify since every detail is already written

**Comment by Code1705** [comment]
to make it more compact and the contribution process in simple language , please could you assign me under JWOC.

**Comment by Rakesh9100** [comment]
You can go ahead but if the work will not be much beneficial for the Readme, then it will not be approved @Code1705

**Comment by Code1705** [comment]
kindly assign me under JWOC.

**Comment by Code1705** [comment]
@Rakesh9100 I have updated the readme file with hyperlinks , content and updated screenshots of the page of the game , please could you merge ,my PR?

**Comment by Rakesh9100** [comment]
See the comment and work on it @Code1705
