### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Akanksha-Sen** [Rakesh9100/Click-The-Edible-Game#36]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add footer to the website.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
It's not required for now.
