### ISSUE TITLE
Navigation & Footer 

### ISSUE THREAD

**Issue by Keshab1113** [Rakesh9100/Click-The-Edible-Game#46]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add a Footer and navigation section for this game under JWOC

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Pls specify what navigation you want to add?

**Comment by Keshab1113** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/110785343/219934647-ce5e71f1-2bd2-434d-8002-c17f7855fc2b.png)
This type of navigation i want to add in your web, please assign me

**Comment by Keshab1113** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/110785343/219934712-017cc740-5f16-4389-92e4-44df56355176.png)
This type of footer i want to add, please assign me

**Comment by Rakesh9100** [comment]
Navigation is not needed since there are not many sections.
You can go for the footer and make it properly and responsive so that it should not affect the game @Keshab1113

**Comment by Keshab1113** [comment]
Okey, assign me
