### ISSUE TITLE
Sign in & Sign up 

### ISSUE THREAD

**Issue by Keshab1113** [Rakesh9100/Click-The-Edible-Game#47]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add sign in and sign up button on the top Under JWOC

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
It's a gaming project, so no sign in and sign up required. If you have any good idea regarding this, then specify in detail.
