### ISSUE TITLE
Enhance the color

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/Click-The-Edible-Game#48]
Enhance the background color of just the Landing Page (refer below).

![image](https://user-images.githubusercontent.com/73993775/219845648-0f8a67e7-48ee-4ebb-a57b-189b8a2644ba.png)

**Comment by AK-shat-JAIN** [comment]
Hello @Rakesh9100  I wish to do this task 
Can you more specifically what type of colour enhancement you want

**Comment by Rakesh9100** [comment]
You can see that Background of landing page and home page looks same(similar). So change accordingly so that both look good and different.

**Comment by Rakesh9100** [comment]
Are you working @AK-shat-JAIN

**Comment by AK-shat-JAIN** [comment]
Yes I will generate PR by 1-2hrs

**Comment by Rakesh9100** [comment]
No issues, you have your time. Continue your work.

**Comment by AK-shat-JAIN** [comment]
Thank you Sr 
Sr I think because or the white text a Darker background will be more suitable that's why I choose to use the color of background of Dark theme with a Purple tint 

Will it be ok?

**Comment by Rakesh9100** [comment]
It's your wish. I will see when you will make final PR or can send SS here if you want to show.

**Comment by AK-shat-JAIN** [comment]
ok sr

**Comment by AK-shat-JAIN** [comment]
I have make border of two colour gradient 

without text:
![image](https://user-images.githubusercontent.com/84455686/219884043-7e365908-5aa0-450e-bc89-586ca883fcbb.png)

With text:
![image](https://user-images.githubusercontent.com/84455686/219884068-64ed2776-e15b-4e6b-90ab-6e3684b673c4.png)

Sr please suggest me with any changes if required

**Comment by AK-shat-JAIN** [comment]
Sir can you tell anything else required in addition to above screenshots or its fine

**Comment by Rakesh9100** [comment]
It's fine @AK-shat-JAIN

**Comment by AK-shat-JAIN** [comment]
ok Thanks @Rakesh9100
