### ISSUE TITLE
Add a Contributing.md file

### ISSUE THREAD

**Issue by RathoreAbhiii** [Rakesh9100/Click-The-Edible-Game#5]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

This repository needs  a Contributing.md file in order to be eligible for hacktoberfest 2022. Please add the same file to the root directory or @Rakesh9100 assign me this issue as I can update it with the suitable information required.
Thanks!

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
It's already present here [CG](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md), so work on another issue @RathoreAbhiii
