### ISSUE TITLE
Make Landing page mobile responsive

### ISSUE THREAD

**Issue by AK-shat-JAIN** [Rakesh9100/Click-The-Edible-Game#61]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

There is no space in between edge and text in starting landing page 

give proper media query according to the mobile size screen so text rescale

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Pls highlight what issue you are trying to specify in the Screenshot @AK-shat-JAIN

**Comment by AK-shat-JAIN** [comment]
![image](https://user-images.githubusercontent.com/84455686/220035958-7783347f-b2bf-4390-b827-054901784fea.png)

give some left-right margins in this so look great from mobile view also

**Comment by Rakesh9100** [comment]
No, it's already responsive @AK-shat-JAIN, I suppose it's not needed.

**Comment by AK-shat-JAIN** [comment]
ok sr, I thought it would look nice if in mobile view border thickness reduce and there is some space between text and boarder as they are touching now
