### ISSUE TITLE
Add Footer

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/Click-The-Edible-Game#66]
Add a responsive footer to the website and make sure it should not affect any page screen or gameplay.

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by Rakesh9100** [comment]
Go ahead @Hritik1503

**Comment by Hritik1503** [comment]
yes i will complete this task

**Comment by Hritik1503** [comment]
ok what type of details add in footer please tell me

**Comment by Rakesh9100** [comment]
Just simple like this.
Copyright © 2023 by Rakesh Roshan. All Rights Reserved.

**Comment by Hritik1503** [comment]
I will complete this task if any change required tell me .I will send you
edited screenshot of the edible game.

**Comment by Rakesh9100** [comment]
How can I say the changes? Where is the SS ?

**Comment by Hritik1503** [comment]
scrreenshot is i will send you in previous mail

**Comment by Hritik1503** [comment]
check this in darkmode just like this
![Uploading Screenshot (14).png…]()

**Comment by Hritik1503** [comment]
![Screenshot (14)](https://user-images.githubusercontent.com/67685634/220396841-b1eb3014-aa29-404d-8bba-2a4c9efb199c.png)
