### ISSUE TITLE
Adding a Home Icon 

### ISSUE THREAD

**Issue by YashBawa** [Rakesh9100/Click-The-Edible-Game#7]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

A home icon should be added to the top right corner of the website. To help users reload or jump directly to the home page using it. 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by YashBawa** [comment]
Please assign this issue under the Hacktoberfest label as I want to work on it. Thank you @Rakesh9100

**Comment by YashBawa** [comment]
Ok @Rakesh9100 , Thanks

**Comment by Rakesh9100** [comment]
Any update ? @YashBawa

**Comment by YashBawa** [comment]
Yes will make a PR by tonight
