### ISSUE TITLE
right click restrict on the game page

### ISSUE THREAD

**Issue by suman-tewary** [Rakesh9100/Click-The-Edible-Game#70]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Restrict the right-click on the game page.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Ok, go ahead, Assigned @suman-tewary
