### ISSUE TITLE
Instructions should be there to guide the beginners how to play 

### ISSUE THREAD

**Issue by priyanka1551** [Rakesh9100/Click-The-Edible-Game#76]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

As I saw this game for the first time. Even after playing it for many times , it didn't get how to play this game. So, I want that there should be proper instructions for the new users.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by priyanka1551** [comment]
I want to work on this issue under JWOC

**Comment by Rakesh9100** [comment]
Sure, Assigned to you @priyanka1551

**Comment by priyanka1551** [comment]
@Rakesh9100 please add tag to this issue whether its an easy, medium or hard tag

**Comment by Rakesh9100** [comment]
Labelling Medium tag but will change depending on the LOC and enhancement you make @priyanka1551

**Comment by priyanka1551** [comment]
> Labelling Medium tag but can change depending on the LOC and enhancement you make @priyanka1551

But this is not the criteria. Labelling is done before based on the issue and no mentor can change it depending on the length of code

**Comment by Rakesh9100** [comment]
Labelling is done before, so I labeled as medium but if suppose issue is opened to make the site as dark mode, so this issue will be Medium Level but if mentee only gives toggle button, so it will be easy level, but another mentee who gives button and also customize color depending on the theme and enhances so he/she will get Medium Level. Hope it's clear. @priyanka1551

**Comment by Rakesh9100** [comment]
You work on and don't worry on label. Every mentee will get label awarded as per the work.

**Comment by priyanka1551** [comment]
> You work on and don't worry on label. Every mentee will get label awarded as per the work.

okyyyy

**Comment by priyanka1551** [comment]
Can you please tell me the condition of wining in this game as I am not getting how to play

**Comment by Rakesh9100** [comment]
This is a time-passing game made by me. It's not about any win or loss. Just if you are bored, then play the game by selecting different different edibles and enjoy.
If you have the idea to make this game to win and loss, then you can create issues in the future.

**Comment by priyanka1551** [comment]
> This is a time-passing game made by me. It's not about any win or loss. Just if you are bored, then play the game by selecting different different edibles and enjoy. If you have the idea to make this game to win and loss or high scores or anything new feature, then you can create issues in the future.

Okayyyyyy ... I will think about this

**Comment by priyanka1551** [comment]
Just an update. I will make pr by tomorrow for sure.

**Comment by Rakesh9100** [comment]
Okay

**Comment by priyanka1551** [comment]
@Rakesh9100 Can I add instruction button here?
![Screenshot (159)](https://user-images.githubusercontent.com/105537443/221424832-9d007b26-f406-4dce-ba16-4a33161f2ec9.png)

**Comment by Rakesh9100** [comment]
No, there should be a small i button inside some designed shape like which would flash the instructions when clicked and this button should be visible in every screen.
You can put beside that play pause button, but should be visible in every screen. @priyanka1551

**Comment by priyanka1551** [comment]
> No, there should be a small i button inside some designed shape like which would flash the instructions when clicked and this button should be visible in every screen. You can put beside that play pause button, but should be visible in every screen. @priyanka1551

I am not able to understand where to put this instruction button. Can you show me some example how this should look like?

**Comment by Rakesh9100** [comment]
![1](https://user-images.githubusercontent.com/73993775/221604617-faecc494-99cc-4a22-8d89-d682e2c2eac3.png)

You can put the simple designed i button in that purple place beside that play pause button, but this button should be visible in every screen. And this when clicked should flash up the instructions in a proper designed box. @priyanka1551

**Comment by pooranjoyb** [comment]
I would like to work on this issue. Would be great you'd assign me with this issue @Rakesh9100

**Comment by pooranjoyb** [comment]
Also I am planning to add a popup window similar to `gameover` and `pause-menu`. Would do you say bhaiya? @Rakesh9100

**Comment by Rakesh9100** [comment]
Assigning to you @pooranjoyb Start working

**Comment by mecivil** [comment]
I want to work on this under JWOC

**Comment by ManasaKaza** [comment]
I want to work on this Issue under JWOC
