### ISSUE TITLE
Improvement of Page Responsiveness

### ISSUE THREAD

**Issue by TuhinBanerjee31** [Rakesh9100/Click-The-Edible-Game#77]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to work on this issue under JWOC. 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead @TuhinBanerjee31
