### ISSUE TITLE
Watermelon image dimensions resize

### ISSUE THREAD

**Issue by AK-shat-JAIN** [Rakesh9100/Click-The-Edible-Game#79]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Image of watermelon looking to be stretched out 
Rewrite its height and width parameter to make it ok

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Work on, assigned @AK-shat-JAIN

**Comment by AK-shat-JAIN** [comment]
Thanks Sr
