### ISSUE TITLE
Make the game fully responsive

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/Click-The-Edible-Game#8]

**Comment by GeorgeET15** [comment]
Hi, I would like to work on this issue can you assign this to me please. Thank you

**Comment by Rakesh9100** [comment]
Yes Sure !!

**Comment by GeorgeET15** [comment]
> Yes Sure !! Are you working under Hacktoberfest ? @GeorgeET15

Yes

**Comment by Rakesh9100** [comment]
Okay proceed.

**Comment by Rakesh9100** [comment]
Issues will be assigned from 15th. Till then, go through the codebase and create new issues.

**Comment by EmberTSeal** [comment]
I would like to work on this.

**Comment by SasiVardhan247** [comment]
I want to work on this issue under JWOC

**Comment by anvi2901** [comment]
I want to work on this issue under JWOC!

**Comment by ManasaKaza** [comment]
I want to work on this issue under JWOC

**Comment by Rakesh9100** [comment]
@SasiVardhan247 Assigning this issue to you, go ahead

**Comment by Rakesh9100** [comment]
@SasiVardhan247 Status of your work

**Comment by deepbeatz** [comment]
I want to work on this under JWOC
