### ISSUE TITLE
Enhancing by Deciding a Final Score when the timer ends 

### ISSUE THREAD

**Issue by pooranjoyb** [Rakesh9100/Click-The-Edible-Game#81]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### I saw that this game tends to an infinite loop while playing. 
As you already said that you've made this game for just fun, I felt like it would be great if 
- there's a time ticking down and player gets to click as many fruits as possible until the timer ends. 
- As of now the timer has nothing to do with the timer as it never stops, but with this enhancement it won't be an infinite loop game.
- That will be awesome as we'll be able to decide a winner based on scores after that.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by pooranjoyb** [comment]
### I would like to work on this issue under JWOC 2023. Would be glad if you'd assign me with this issue. 👍  @Rakesh9100

**Comment by Rakesh9100** [comment]
Sure, you can work on. In fact, I was about to open this issue in Phase 2.
Assigning to you @pooranjoyb

**Comment by pooranjoyb** [comment]
Thanks for assigning @Rakesh9100 .
Getting into it Asap! :) 👍
