### ISSUE TITLE
Add a visual effect to slice the fruits or vegetables

### ISSUE THREAD

**Issue by ayushanand308** [Rakesh9100/Click-The-Edible-Game#82]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

We can add a nice visual effect of slicing the chosen fruit/vegetable to make the game look better.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by ayushanand308** [comment]
@Rakesh9100 Please assign me this issue under JWOC

**Comment by Rakesh9100** [comment]
Can you pls brief what slicing effect? Show any reference if any.

**Comment by ayushanand308** [comment]
@Rakesh9100 
![image](https://user-images.githubusercontent.com/99035102/221432692-f73d606f-3f9e-4106-9af1-6bfaef24f141.png)

Something like this but not that much graphic intensive.

**Comment by Rakesh9100** [comment]
I suppose this is not needed. It's fine as it is. Try to find and work on other issues.
