### ISSUE TITLE
 UI Modification : header not visible

### ISSUE THREAD

**Issue by PurviSaini** [Rakesh9100/Click-The-Edible-Game#90]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

There needs to be a change in the UI of the website.
If this is a noticeable change then could I work on this issue under JWOC?

### Screenshots

header with the text "choose your favorite fruit" is not visible

![Screenshot (48)](https://user-images.githubusercontent.com/101940722/222844339-cfecd5ce-1521-4937-9c78-170bba1e30e6.png)

header should be like this:

![Screenshot (47)](https://user-images.githubusercontent.com/101940722/222844576-2247bbd5-6f77-4880-9a5b-e7a93fb1a2e3.png)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Is this the problem when you inspected the element ? Is it the responsiveness issue you are trying to specify ? @PurviSaini

**Comment by PurviSaini** [comment]
When I opened the project on chrome, it appeared to be like, shown in the first screenshot and when the width of the screen changes then also the header gets hidden

**Comment by PurviSaini** [comment]
in short problem is related to responsiveness as you said, I believe.

**Comment by Rakesh9100** [comment]
Okay then proceed to work and make this website fully proper responsive and do check with respect to all size devices@PurviSaini

**Comment by PurviSaini** [comment]
okay, Thankyou for considering!

**Comment by PurviSaini** [comment]
Is it alright?

https://user-images.githubusercontent.com/101940722/222904115-54dcd085-8166-4860-b80c-fd9f6fd1421d.mp4
