### ISSUE TITLE
Creat testimonial page

### ISSUE THREAD

**Issue by Neha00011** [Rakesh9100/Click-The-Edible-Game#94]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add a testimonial page where players can see the reviews of other players.Kindly assign this issue to me under JWOC.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Not required. Kindly work on other issues.
