### ISSUE TITLE
Heading not showing

### ISSUE THREAD

**Issue by suman-tewary** [Rakesh9100/Click-The-Edible-Game#95]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

In the game, item selection page the top heading is not showing
<img width="925" alt="image" src="https://user-images.githubusercontent.com/43510749/222980213-1006b2c9-3008-471e-8323-b5fe8146ef80.png">

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
No it's fine. Check again @suman-tewary

**Comment by suman-tewary** [comment]
Its a problem in other screen-size devices
Zoom your screen little you will understand the problem
