### ISSUE TITLE
[Feature] Adding a Funtionality to choose Time of Gameplay

### ISSUE THREAD

**Issue by pooranjoyb** [Rakesh9100/Click-The-Edible-Game#97]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

## Workflow :
- I would create a method which will be triggered when user chooses the fruit/veggie he/she would like to play with
- With respect to that I will be able to manipulate the `gameplay time`.

I would like to work on this issue under JWOC '2023. Would be glad if you'd assign me this issue. @Rakesh9100 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Sure, go ahead @pooranjoyb
