### ISSUE TITLE
Add badges in readme

### ISSUE THREAD

**Issue by khushimarothi** [Rakesh9100/Click-The-Edible-Game#98]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

want to add badges in the readme.
please assign under jwoc

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Which badge? Pls specify clearly @khushimarothi

**Comment by khushimarothi** [comment]
![Screenshot (38)](https://user-images.githubusercontent.com/85816852/223619464-148ac4df-337d-4948-9afc-5e9560f63551.png)
Like this

**Comment by Rakesh9100** [comment]
Okay go ahead. Put in proper format.
